//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.WebAPI.AtlasNetcallWebservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountDetail", Namespace="urn:netcall")]
    [System.SerializableAttribute()]
    public partial class AccountDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIDField;
        
        private int AmountToPayField;
        
        private System.DateTime CourseDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseVenueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShopperReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResultDescription {
            get {
                return this.ResultDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultDescriptionField, value) != true)) {
                    this.ResultDescriptionField = value;
                    this.RaisePropertyChanged("ResultDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIDField, value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int AmountToPay {
            get {
                return this.AmountToPayField;
            }
            set {
                if ((this.AmountToPayField.Equals(value) != true)) {
                    this.AmountToPayField = value;
                    this.RaisePropertyChanged("AmountToPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime CourseDateTime {
            get {
                return this.CourseDateTimeField;
            }
            set {
                if ((this.CourseDateTimeField.Equals(value) != true)) {
                    this.CourseDateTimeField = value;
                    this.RaisePropertyChanged("CourseDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CourseVenue {
            get {
                return this.CourseVenueField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseVenueField, value) != true)) {
                    this.CourseVenueField = value;
                    this.RaisePropertyChanged("CourseVenue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ShopperReference {
            get {
                return this.ShopperReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ShopperReferenceField, value) != true)) {
                    this.ShopperReferenceField = value;
                    this.RaisePropertyChanged("ShopperReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountPaymentResult", Namespace="urn:netcall")]
    [System.SerializableAttribute()]
    public partial class AccountPaymentResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResultDescription {
            get {
                return this.ResultDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultDescriptionField, value) != true)) {
                    this.ResultDescriptionField = value;
                    this.RaisePropertyChanged("ResultDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:netcall", ConfigurationName="AtlasNetcallWebservice.NetcallSoap")]
    public interface NetcallSoap {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:tppayments) of message GetAccountDetailsRequest does not match the default value (urn:netcall)
        [System.ServiceModel.OperationContractAttribute(Action="urn:netcall/GetAccountDetails", ReplyAction="*")]
        IAM.Atlas.WebAPI.AtlasNetcallWebservice.GetAccountDetailsResponse GetAccountDetails(IAM.Atlas.WebAPI.AtlasNetcallWebservice.GetAccountDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:netcall/GetAccountDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<IAM.Atlas.WebAPI.AtlasNetcallWebservice.GetAccountDetailsResponse> GetAccountDetailsAsync(IAM.Atlas.WebAPI.AtlasNetcallWebservice.GetAccountDetailsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:tppayments) of message PostAccountPaymentResultRequest does not match the default value (urn:netcall)
        [System.ServiceModel.OperationContractAttribute(Action="urn:netcall/PostAccountPaymentResult", ReplyAction="*")]
        IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultResponse PostAccountPaymentResult(IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:netcall/PostAccountPaymentResult", ReplyAction="*")]
        System.Threading.Tasks.Task<IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultResponse> PostAccountPaymentResultAsync(IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:tppayments) of message PostAccountPaymentResultOldRequest does not match the default value (urn:netcall)
        [System.ServiceModel.OperationContractAttribute(Action="urn:netcall/PostAccountPaymentResultOld", ReplyAction="*")]
        IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultOldResponse PostAccountPaymentResultOld(IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultOldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:netcall/PostAccountPaymentResultOld", ReplyAction="*")]
        System.Threading.Tasks.Task<IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultOldResponse> PostAccountPaymentResultOldAsync(IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultOldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountDetails", WrapperNamespace="urn:tppayments", IsWrapped=true)]
    public partial class GetAccountDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RequestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string RequestTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string CallingNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string AppContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string ClientID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string DOB;
        
        public GetAccountDetailsRequest() {
        }
        
        public GetAccountDetailsRequest(string RequestID, string RequestTime, string CallingNumber, string AppContext, string ClientID, string DOB) {
            this.RequestID = RequestID;
            this.RequestTime = RequestTime;
            this.CallingNumber = CallingNumber;
            this.AppContext = AppContext;
            this.ClientID = ClientID;
            this.DOB = DOB;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountDetailsResponse", WrapperNamespace="urn:netcall", IsWrapped=true)]
    public partial class GetAccountDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public IAM.Atlas.WebAPI.AtlasNetcallWebservice.AccountDetail GetAccountDetailsResult;
        
        public GetAccountDetailsResponse() {
        }
        
        public GetAccountDetailsResponse(IAM.Atlas.WebAPI.AtlasNetcallWebservice.AccountDetail GetAccountDetailsResult) {
            this.GetAccountDetailsResult = GetAccountDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostAccountPaymentResult", WrapperNamespace="urn:tppayments", IsWrapped=true)]
    public partial class PostAccountPaymentResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RequestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string RequestTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string CallingNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string AppContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string ClientID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string PaymentResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string AuthorisationReference;
        
        public PostAccountPaymentResultRequest() {
        }
        
        public PostAccountPaymentResultRequest(string RequestID, string RequestTime, string CallingNumber, string AppContext, string ClientID, string PaymentResult, string AuthorisationReference) {
            this.RequestID = RequestID;
            this.RequestTime = RequestTime;
            this.CallingNumber = CallingNumber;
            this.AppContext = AppContext;
            this.ClientID = ClientID;
            this.PaymentResult = PaymentResult;
            this.AuthorisationReference = AuthorisationReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostAccountPaymentResultResponse", WrapperNamespace="urn:netcall", IsWrapped=true)]
    public partial class PostAccountPaymentResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public IAM.Atlas.WebAPI.AtlasNetcallWebservice.AccountPaymentResult PostAccountPaymentResultResult;
        
        public PostAccountPaymentResultResponse() {
        }
        
        public PostAccountPaymentResultResponse(IAM.Atlas.WebAPI.AtlasNetcallWebservice.AccountPaymentResult PostAccountPaymentResultResult) {
            this.PostAccountPaymentResultResult = PostAccountPaymentResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostAccountPaymentResultOld", WrapperNamespace="urn:tppayments", IsWrapped=true)]
    public partial class PostAccountPaymentResultOldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string RequestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string RequestTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string CallingNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string AppContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string ClientID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string PaymentResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string AuthorisationReference;
        
        public PostAccountPaymentResultOldRequest() {
        }
        
        public PostAccountPaymentResultOldRequest(string RequestID, string RequestTime, string CallingNumber, string AppContext, string ClientID, string PaymentResult, string AuthorisationReference) {
            this.RequestID = RequestID;
            this.RequestTime = RequestTime;
            this.CallingNumber = CallingNumber;
            this.AppContext = AppContext;
            this.ClientID = ClientID;
            this.PaymentResult = PaymentResult;
            this.AuthorisationReference = AuthorisationReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostAccountPaymentResultOldResponse", WrapperNamespace="urn:netcall", IsWrapped=true)]
    public partial class PostAccountPaymentResultOldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public IAM.Atlas.WebAPI.AtlasNetcallWebservice.AccountPaymentResult PostAccountPaymentResultOldResult;
        
        public PostAccountPaymentResultOldResponse() {
        }
        
        public PostAccountPaymentResultOldResponse(IAM.Atlas.WebAPI.AtlasNetcallWebservice.AccountPaymentResult PostAccountPaymentResultOldResult) {
            this.PostAccountPaymentResultOldResult = PostAccountPaymentResultOldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NetcallSoapChannel : IAM.Atlas.WebAPI.AtlasNetcallWebservice.NetcallSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NetcallSoapClient : System.ServiceModel.ClientBase<IAM.Atlas.WebAPI.AtlasNetcallWebservice.NetcallSoap>, IAM.Atlas.WebAPI.AtlasNetcallWebservice.NetcallSoap {
        
        public NetcallSoapClient() {
        }
        
        public NetcallSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NetcallSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NetcallSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NetcallSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IAM.Atlas.WebAPI.AtlasNetcallWebservice.GetAccountDetailsResponse IAM.Atlas.WebAPI.AtlasNetcallWebservice.NetcallSoap.GetAccountDetails(IAM.Atlas.WebAPI.AtlasNetcallWebservice.GetAccountDetailsRequest request) {
            return base.Channel.GetAccountDetails(request);
        }
        
        public IAM.Atlas.WebAPI.AtlasNetcallWebservice.AccountDetail GetAccountDetails(string RequestID, string RequestTime, string CallingNumber, string AppContext, string ClientID, string DOB) {
            IAM.Atlas.WebAPI.AtlasNetcallWebservice.GetAccountDetailsRequest inValue = new IAM.Atlas.WebAPI.AtlasNetcallWebservice.GetAccountDetailsRequest();
            inValue.RequestID = RequestID;
            inValue.RequestTime = RequestTime;
            inValue.CallingNumber = CallingNumber;
            inValue.AppContext = AppContext;
            inValue.ClientID = ClientID;
            inValue.DOB = DOB;
            IAM.Atlas.WebAPI.AtlasNetcallWebservice.GetAccountDetailsResponse retVal = ((IAM.Atlas.WebAPI.AtlasNetcallWebservice.NetcallSoap)(this)).GetAccountDetails(inValue);
            return retVal.GetAccountDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IAM.Atlas.WebAPI.AtlasNetcallWebservice.GetAccountDetailsResponse> IAM.Atlas.WebAPI.AtlasNetcallWebservice.NetcallSoap.GetAccountDetailsAsync(IAM.Atlas.WebAPI.AtlasNetcallWebservice.GetAccountDetailsRequest request) {
            return base.Channel.GetAccountDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IAM.Atlas.WebAPI.AtlasNetcallWebservice.GetAccountDetailsResponse> GetAccountDetailsAsync(string RequestID, string RequestTime, string CallingNumber, string AppContext, string ClientID, string DOB) {
            IAM.Atlas.WebAPI.AtlasNetcallWebservice.GetAccountDetailsRequest inValue = new IAM.Atlas.WebAPI.AtlasNetcallWebservice.GetAccountDetailsRequest();
            inValue.RequestID = RequestID;
            inValue.RequestTime = RequestTime;
            inValue.CallingNumber = CallingNumber;
            inValue.AppContext = AppContext;
            inValue.ClientID = ClientID;
            inValue.DOB = DOB;
            return ((IAM.Atlas.WebAPI.AtlasNetcallWebservice.NetcallSoap)(this)).GetAccountDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultResponse IAM.Atlas.WebAPI.AtlasNetcallWebservice.NetcallSoap.PostAccountPaymentResult(IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultRequest request) {
            return base.Channel.PostAccountPaymentResult(request);
        }
        
        public IAM.Atlas.WebAPI.AtlasNetcallWebservice.AccountPaymentResult PostAccountPaymentResult(string RequestID, string RequestTime, string CallingNumber, string AppContext, string ClientID, string PaymentResult, string AuthorisationReference) {
            IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultRequest inValue = new IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultRequest();
            inValue.RequestID = RequestID;
            inValue.RequestTime = RequestTime;
            inValue.CallingNumber = CallingNumber;
            inValue.AppContext = AppContext;
            inValue.ClientID = ClientID;
            inValue.PaymentResult = PaymentResult;
            inValue.AuthorisationReference = AuthorisationReference;
            IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultResponse retVal = ((IAM.Atlas.WebAPI.AtlasNetcallWebservice.NetcallSoap)(this)).PostAccountPaymentResult(inValue);
            return retVal.PostAccountPaymentResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultResponse> IAM.Atlas.WebAPI.AtlasNetcallWebservice.NetcallSoap.PostAccountPaymentResultAsync(IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultRequest request) {
            return base.Channel.PostAccountPaymentResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultResponse> PostAccountPaymentResultAsync(string RequestID, string RequestTime, string CallingNumber, string AppContext, string ClientID, string PaymentResult, string AuthorisationReference) {
            IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultRequest inValue = new IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultRequest();
            inValue.RequestID = RequestID;
            inValue.RequestTime = RequestTime;
            inValue.CallingNumber = CallingNumber;
            inValue.AppContext = AppContext;
            inValue.ClientID = ClientID;
            inValue.PaymentResult = PaymentResult;
            inValue.AuthorisationReference = AuthorisationReference;
            return ((IAM.Atlas.WebAPI.AtlasNetcallWebservice.NetcallSoap)(this)).PostAccountPaymentResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultOldResponse IAM.Atlas.WebAPI.AtlasNetcallWebservice.NetcallSoap.PostAccountPaymentResultOld(IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultOldRequest request) {
            return base.Channel.PostAccountPaymentResultOld(request);
        }
        
        public IAM.Atlas.WebAPI.AtlasNetcallWebservice.AccountPaymentResult PostAccountPaymentResultOld(string RequestID, string RequestTime, string CallingNumber, string AppContext, string ClientID, string PaymentResult, string AuthorisationReference) {
            IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultOldRequest inValue = new IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultOldRequest();
            inValue.RequestID = RequestID;
            inValue.RequestTime = RequestTime;
            inValue.CallingNumber = CallingNumber;
            inValue.AppContext = AppContext;
            inValue.ClientID = ClientID;
            inValue.PaymentResult = PaymentResult;
            inValue.AuthorisationReference = AuthorisationReference;
            IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultOldResponse retVal = ((IAM.Atlas.WebAPI.AtlasNetcallWebservice.NetcallSoap)(this)).PostAccountPaymentResultOld(inValue);
            return retVal.PostAccountPaymentResultOldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultOldResponse> IAM.Atlas.WebAPI.AtlasNetcallWebservice.NetcallSoap.PostAccountPaymentResultOldAsync(IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultOldRequest request) {
            return base.Channel.PostAccountPaymentResultOldAsync(request);
        }
        
        public System.Threading.Tasks.Task<IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultOldResponse> PostAccountPaymentResultOldAsync(string RequestID, string RequestTime, string CallingNumber, string AppContext, string ClientID, string PaymentResult, string AuthorisationReference) {
            IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultOldRequest inValue = new IAM.Atlas.WebAPI.AtlasNetcallWebservice.PostAccountPaymentResultOldRequest();
            inValue.RequestID = RequestID;
            inValue.RequestTime = RequestTime;
            inValue.CallingNumber = CallingNumber;
            inValue.AppContext = AppContext;
            inValue.ClientID = ClientID;
            inValue.PaymentResult = PaymentResult;
            inValue.AuthorisationReference = AuthorisationReference;
            return ((IAM.Atlas.WebAPI.AtlasNetcallWebservice.NetcallSoap)(this)).PostAccountPaymentResultOldAsync(inValue);
        }
    }
}
