

INSERT INTO [dbo].[ReferringAuthority] (
		[Name]
		, [Description]
		, [Disabled]
		, AssociatedOrganisationId
		, CreatedByUserId
		, DateCreated
		, UpdatedByUserId
		, DateUpdated
		)
SELECT 
	RAS.RA						AS [Name]
	, RAS.RA					AS [Description]
	, 'False'					AS [Disabled]
	, O.Id						AS AssociatedOrganisationId
	, dbo.udfGetSystemUserId()	AS CreatedByUserId
	, GETDATE()					AS DateCreated
	, dbo.udfGetSystemUserId()	AS UpdatedByUserId
	, GETDATE()					AS DateUpdated
FROM (
	SELECT 'AVON AND SOMERSET CONSTABULARY' AS RA, 'Avon & Somerset Constabulary' AS ALT_Name1, 'Avon & Somerset Constabulary' AS ALT_Name2
	UNION SELECT 'BEDFORDSHIRE POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'CAMBRIDGESHIRE CONSTABULARY' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'CHESHIRE' AS RA, 'Cheshire Constabulary' AS ALT_Name1, 'TestUpdate12345' AS ALT_Name2
	UNION SELECT 'CITY OF LONDON POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'CLEVELAND POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'CUMBRIA CONSTABULARY' AS RA, 'Cumbria Police' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'DERBYSHIRE CONSTABULARY' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'DEVON AND CORNWALL CONSTABULARY' AS RA, 'Devon & Cornwall Constabulary' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'DORSET POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'DURHAM CONSTABULARY' AS RA, 'Durham Police' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'DYFED-POWYS POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'ESSEX POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'GLOUCESTERSHIRE CONSTABULARY' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'GREATER MANCHESTER POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'GWENT POLICE' AS RA, 'Gwent Police Authority' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'HAMPSHIRE CONSTABULARY' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'HERTFORDSHIRE CONSTABULARY' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'HUMBERSIDE POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'KENT COUNTY POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'LANCASHIRE CONSTABULARY' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'LEICESTERSHIRE CONSTABULARY' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'LINCOLNSHIRE POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'MERSEYSIDE POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'METROPOLITAN POLICE' AS RA, 'Metropolitan Police' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'NORFOLK CONSTABULARY' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'NORTH WALES POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'NORTH YORKSHIRE POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'NORTHAMPTONSHIRE POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'NORTHUMBRIA POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'NOTTINGHAMSHIRE POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'POLICE SERVICE NORTHERN IRELAND' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'SCOTLAND RSS' AS RA, 'Scotland (RSS)' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'SOUTH WALES POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'SOUTH YORKSHIRE POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'STAFFORDSHIRE POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'SUFFOLK CONSTABULARY' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'SURREY POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'SUSSEX POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'THAMES VALLEY POLICE' AS RA, 'Thames Valley Police (Berkshire)' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'WARWICKSHIRE POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'WEST MERCIA CONSTABULARY' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'WEST MIDLANDS POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'WEST YORKSHIRE POLICE' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'WILTSHIRE CONSTABULARY' AS RA, 'Wiltshire Police' AS ALT_Name1, '' AS ALT_Name2
	UNION SELECT 'FANTASIA SAFETY SERVICES' AS RA, '' AS ALT_Name1, '' AS ALT_Name2
	) AS RAS
INNER JOIN Organisation O ON O.[Name] = RAS.RA
							OR O.[Name] = RAS.ALT_Name1
							OR O.[Name] = RAS.ALT_Name2
LEFT JOIN [dbo].[ReferringAuthority] RA ON RA.AssociatedOrganisationId = O.Id
WHERE RA.Id IS NULL
;


