

UPDATE O
SET O.Active = 'False'
FROM (
	SELECT 'Alfriston' AS [Name]
	UNION SELECT 'All Saints And St Richards' AS [Name]
	UNION SELECT 'All Saints C of E Junior School, Hastings' AS [Name]
	UNION SELECT 'All Saints C of E Primary School, Bexhill' AS [Name]
	UNION SELECT 'Annecy Catholic Primary School' AS [Name]
	UNION SELECT 'Barcombe' AS [Name]
	UNION SELECT 'Battle & Langton' AS [Name]
	UNION SELECT 'Beckley' AS [Name]
	UNION SELECT 'Blackboys' AS [Name]
	UNION SELECT 'Blacklands' AS [Name]
	UNION SELECT 'Bodiam' AS [Name]
	UNION SELECT 'Bonners' AS [Name]
	UNION SELECT 'Bourne' AS [Name]
	UNION SELECT 'Brede' AS [Name]
	UNION SELECT 'Broad Oak' AS [Name]
	UNION SELECT 'BSM' AS [Name]
	UNION SELECT 'Burwash' AS [Name]
	UNION SELECT 'Buxted' AS [Name]
	UNION SELECT 'Cambridgeshire County Council' AS [Name]
	UNION SELECT 'Carmarthenshire County Council' AS [Name]
	UNION SELECT 'Castledown' AS [Name]
	UNION SELECT 'Catsfield' AS [Name]
	UNION SELECT 'Chantry' AS [Name]
	UNION SELECT 'Cheshire Constabulary (SP)' AS [Name]
	UNION SELECT 'Cheshire West and Chester Council' AS [Name]
	UNION SELECT 'Chiddingly' AS [Name]
	UNION SELECT 'Christ Church' AS [Name]
	UNION SELECT 'Churchwood' AS [Name]
	UNION SELECT 'Chyngton' AS [Name]
	UNION SELECT 'Cradle Hill' AS [Name]
	UNION SELECT 'Cross in Hand' AS [Name]
	UNION SELECT 'Crowhurst' AS [Name]
	UNION SELECT 'Dallington' AS [Name]
	UNION SELECT 'Danehill' AS [Name]
	UNION SELECT 'Darlington Borough Council' AS [Name]
	UNION SELECT 'Denton' AS [Name]
	UNION SELECT 'Derby City Council' AS [Name]
	UNION SELECT 'Devon & Cornwall Constabulary' AS [Name]
	UNION SELECT 'Devon Drivers Centre' AS [Name]
	UNION SELECT 'Ditchling' AS [Name]
	UNION SELECT 'DriveTech (UK) Plc' AS [Name]
	UNION SELECT 'Driving Services' AS [Name]
	UNION SELECT 'East Hoathly' AS [Name]
	UNION SELECT 'East Sussex Road Safety Unit' AS [Name]
	UNION SELECT 'Elphinstone' AS [Name]
	UNION SELECT 'Enterprise' AS [Name]
	UNION SELECT 'Etchingham' AS [Name]
	UNION SELECT 'Firle' AS [Name]
	UNION SELECT 'Five Ashes' AS [Name]
	UNION SELECT 'Fletching' AS [Name]
	UNION SELECT 'Flintshire County Council' AS [Name]
	UNION SELECT 'Forest Row' AS [Name]
	UNION SELECT 'Framfield' AS [Name]
	UNION SELECT 'Frant' AS [Name]
	UNION SELECT 'GMP Div A - North Manchester' AS [Name]
	UNION SELECT 'GMP Div B - Metropolitan' AS [Name]
	UNION SELECT 'GMP Div C - South Manchester' AS [Name]
	UNION SELECT 'GMP Div F - Swinton' AS [Name]
	UNION SELECT 'GMP Div G - Tameside' AS [Name]
	UNION SELECT 'GMP Div J - Stockport' AS [Name]
	UNION SELECT 'GMP Div K - Bolton' AS [Name]
	UNION SELECT 'GMP Div L - Wigan' AS [Name]
	UNION SELECT 'GMP Div M - Trafford' AS [Name]
	UNION SELECT 'GMP Div N - Bury' AS [Name]
	UNION SELECT 'GMP Div P - Rochdale' AS [Name]
	UNION SELECT 'GMP Div Q - Oldham' AS [Name]
	UNION SELECT 'GP' AS [Name]
	UNION SELECT 'Groombridge' AS [Name]
	UNION SELECT 'Grovelands' AS [Name]
	UNION SELECT 'Guestling Bradshaw' AS [Name]
	UNION SELECT 'Hamsey' AS [Name]
	UNION SELECT 'Hankham' AS [Name]
	UNION SELECT 'Harlands' AS [Name]
	UNION SELECT 'Hawkes Farm' AS [Name]
	UNION SELECT 'Hellingly' AS [Name]
	UNION SELECT 'Herefordshire County Council' AS [Name]
	UNION SELECT 'Herne' AS [Name]
	UNION SELECT 'Herstmonceux' AS [Name]
	UNION SELECT 'Hertfordshire County Council' AS [Name]
	UNION SELECT 'High Hurstwood' AS [Name]
	UNION SELECT 'Highfield Junior' AS [Name]
	UNION SELECT 'Hoddern' AS [Name]
	UNION SELECT 'Hollington' AS [Name]
	UNION SELECT 'Holy Cross' AS [Name]
	UNION SELECT 'Hull City Council' AS [Name]
	UNION SELECT 'Hull County Council' AS [Name]
	UNION SELECT 'Hurst Green' AS [Name]
	UNION SELECT 'I. Ashdown House School' AS [Name]
	UNION SELECT 'I. Battle Abbey School' AS [Name]
	UNION SELECT 'I. Bodiam Manor School' AS [Name]
	UNION SELECT 'I. Bricklehurst Manor School' AS [Name]
	UNION SELECT 'I. Buckswood School' AS [Name]
	UNION SELECT 'I. Chailey Heritage School' AS [Name]
	UNION SELECT 'I. Charters Ancaster College' AS [Name]
	UNION SELECT 'I. Claremont School' AS [Name]
	UNION SELECT 'I. Cumnor House School' AS [Name]
	UNION SELECT 'I. Eastbourne College' AS [Name]
	UNION SELECT 'I. Frewen College' AS [Name]
	UNION SELECT 'I. Greenfields School' AS [Name]
	UNION SELECT 'I. Headstart' AS [Name]
	UNION SELECT 'I. Lewes New School' AS [Name]
	UNION SELECT 'I. Lewes Old Grammar School' AS [Name]
	UNION SELECT 'I. Michael Hall School' AS [Name]
	UNION SELECT 'I. Moira House Girls'' School' AS [Name]
	UNION SELECT 'I. Newlands School' AS [Name]
	UNION SELECT 'I. Northease Manor School' AS [Name]
	UNION SELECT 'I. Owlswick School' AS [Name]
	UNION SELECT 'I. Sacred Heart School' AS [Name]
	UNION SELECT 'I. Skippers Hill Manor School' AS [Name]
	UNION SELECT 'I. St Andrew''s School' AS [Name]
	UNION SELECT 'I. St Bede''s (Preparatory School)' AS [Name]
	UNION SELECT 'I. St Bede''s School' AS [Name]
	UNION SELECT 'I. St Leonards-Mayfield School' AS [Name]
	UNION SELECT 'I. St Mary''s Wrestwood Children''s Trust' AS [Name]
	UNION SELECT 'I. Step by step, School for Autistic Children Ltd' AS [Name]
	UNION SELECT 'I. Vinehall School' AS [Name]
	UNION SELECT 'I. Walsh Manor School' AS [Name]
	UNION SELECT 'Icklesham' AS [Name]
	UNION SELECT 'Iford & Kingston' AS [Name]
	UNION SELECT 'Jarvis Brook' AS [Name]
	UNION SELECT 'KCPA(C)' AS [Name]
	UNION SELECT 'Kent County Council' AS [Name]
	UNION SELECT 'King Offa' AS [Name]
	UNION SELECT 'Kirklees Council' AS [Name]
	UNION SELECT 'Lancashire County Council' AS [Name]
	UNION SELECT 'Langney' AS [Name]
	UNION SELECT 'Laughton' AS [Name]
	UNION SELECT 'Leicester County Council' AS [Name]
	UNION SELECT 'Leicestershire & Rutland SAW' AS [Name]
	UNION SELECT 'Lincolnshire County Council' AS [Name]
	UNION SELECT 'Little Common' AS [Name]
	UNION SELECT 'Little Horsted' AS [Name]
	UNION SELECT 'Little Ridge' AS [Name]
	UNION SELECT 'Logic Software' AS [Name]
	UNION SELECT 'Manor' AS [Name]
	UNION SELECT 'Mark Cross' AS [Name]
	UNION SELECT 'Marshlands' AS [Name]
	UNION SELECT 'Mayfield' AS [Name]
	UNION SELECT 'Maynards Green' AS [Name]
	UNION SELECT 'Media' AS [Name]
	UNION SELECT 'Meeching Valley' AS [Name]
	UNION SELECT 'Meridian' AS [Name]
	UNION SELECT 'Mid and South Wales Safety Camera Partnership' AS [Name]
	UNION SELECT 'Middlesbrough Council' AS [Name]
	UNION SELECT 'Mountfield & Whatlington' AS [Name]
	UNION SELECT 'Neither' AS [Name]
	UNION SELECT 'Netherfield' AS [Name]
	UNION SELECT 'Newick' AS [Name]
	UNION SELECT 'Ninfield' AS [Name]
	UNION SELECT 'No Location' AS [Name]
	UNION SELECT 'Northamptonshire County Council' AS [Name]
	UNION SELECT 'Northiam' AS [Name]
	UNION SELECT 'Northumberland County Council' AS [Name]
	UNION SELECT 'Nottingham City Council' AS [Name]
	UNION SELECT 'Nutley' AS [Name]
	UNION SELECT 'Oakwood' AS [Name]
	UNION SELECT 'Ocklynge' AS [Name]
	UNION SELECT 'Other Location' AS [Name]
	UNION SELECT 'Park Mead' AS [Name]
	UNION SELECT 'Parkland Jnr' AS [Name]
	UNION SELECT 'Parkside' AS [Name]
	UNION SELECT 'Peasmarsh' AS [Name]
	UNION SELECT 'Pebsham' AS [Name]
	UNION SELECT 'Pells' AS [Name]
	UNION SELECT 'Pembrokeshire County Council' AS [Name]
	UNION SELECT 'Pevensey & Westham' AS [Name]
	UNION SELECT 'Plumpton' AS [Name]
	UNION SELECT 'Polegate' AS [Name]
	UNION SELECT 'Police Referral' AS [Name]
	UNION SELECT 'Prodrive 2' AS [Name]
	UNION SELECT 'Prodrive' AS [Name]
	UNION SELECT 'Punnetts Town' AS [Name]
	UNION SELECT 'Recommendation' AS [Name]
	UNION SELECT 'Red Lake' AS [Name]
	UNION SELECT 'Ringmer Primary' AS [Name]
	UNION SELECT 'Robsack Wood' AS [Name]
	UNION SELECT 'Rocks Park' AS [Name]
	UNION SELECT 'Rodmell' AS [Name]
	UNION SELECT 'Rotherfield' AS [Name]
	UNION SELECT 'Rye Primary' AS [Name]
	UNION SELECT 'S. Beacon Community College' AS [Name]
	UNION SELECT 'S. Bexhill High School' AS [Name]
	UNION SELECT 'S. Chailey' AS [Name]
	UNION SELECT 'S. Claverham Community College' AS [Name]
	UNION SELECT 'S. Eastbourne Tech College' AS [Name]
	UNION SELECT 'S. Filsham Valley' AS [Name]
	UNION SELECT 'S. Hailsham Community College' AS [Name]
	UNION SELECT 'S. Heathfield Community College' AS [Name]
	UNION SELECT 'S. Helenswood' AS [Name]
	UNION SELECT 'S. Hillcrest (SOA)' AS [Name]
	UNION SELECT 'S. Peacehaven Community School' AS [Name]
	UNION SELECT 'S. Priory' AS [Name]
	UNION SELECT 'S. Ratton' AS [Name]
	UNION SELECT 'S. Ringmer Community College' AS [Name]
	UNION SELECT 'S. Robertsbridge Community College' AS [Name]
	UNION SELECT 'S. Rye College AKA Thomas Peacocke' AS [Name]
	UNION SELECT 'S. Seaford Head Comm College' AS [Name]
	UNION SELECT 'S. St Richard''s RC College' AS [Name]
	UNION SELECT 'S. The Bishop Bell CE' AS [Name]
	UNION SELECT 'S. The Causeway' AS [Name]
	UNION SELECT 'S. The Cavendish' AS [Name]
	UNION SELECT 'S. The Grove School (St Leonard''s)' AS [Name]
	UNION SELECT 'S. Tideway Community School' AS [Name]
	UNION SELECT 'S. Uckfield Community College' AS [Name]
	UNION SELECT 'S. Uplands Community College' AS [Name]
	UNION SELECT 'S. William Parker (Boys'')' AS [Name]
	UNION SELECT 'S. Willingdon Community School' AS [Name]
	UNION SELECT 'Sacred Heart' AS [Name]
	UNION SELECT 'Sacred Heart RC' AS [Name]
	UNION SELECT 'Salehurst' AS [Name]
	UNION SELECT 'Sandown' AS [Name]
	UNION SELECT 'School' AS [Name]
	UNION SELECT 'Seaford Primary' AS [Name]
	UNION SELECT 'Sedlescombe' AS [Name]
	UNION SELECT 'Shinewater' AS [Name]
	UNION SELECT 'Shropshire County Council' AS [Name]
	UNION SELECT 'Sidley' AS [Name]
	UNION SELECT 'Silverdale' AS [Name]
	UNION SELECT 'Sir Henry Fermor' AS [Name]
	UNION SELECT 'South Malling' AS [Name]
	UNION SELECT 'South Wales Transport Couriers' AS [Name]
	UNION SELECT 'Southdown' AS [Name]
	UNION SELECT 'Southover' AS [Name]
	UNION SELECT 'Sp. Cuckmere House (Seaford)' AS [Name]
	UNION SELECT 'Sp. Glyne Gap (Bexhill)' AS [Name]
	UNION SELECT 'Sp. Grove Park, Crowborough' AS [Name]
	UNION SELECT 'Sp. Hazel Court' AS [Name]
	UNION SELECT 'Sp. New Horizons' AS [Name]
	UNION SELECT 'Sp. Saxon Mount' AS [Name]
	UNION SELECT 'Sp. St Mary''s (Horam, nr Heathfield)' AS [Name]
	UNION SELECT 'Sp. The Lindfield' AS [Name]
	UNION SELECT 'Sp. The South Downs Sp School' AS [Name]
	UNION SELECT 'Sp. Torfield, Hastings' AS [Name]
	UNION SELECT 'St Cyres School' AS [Name]
	UNION SELECT 'St Johns' AS [Name]
	UNION SELECT 'St Johns Meads' AS [Name]
	UNION SELECT 'St Leonards CE' AS [Name]
	UNION SELECT 'St Marks Hadlow Down' AS [Name]
	UNION SELECT 'St Mary Magdalene' AS [Name]
	UNION SELECT 'St Mary Star' AS [Name]
	UNION SELECT 'St Mary the Virgin' AS [Name]
	UNION SELECT 'St Marys RC' AS [Name]
	UNION SELECT 'St Michael' AS [Name]
	UNION SELECT 'St Michaels Withyham' AS [Name]
	UNION SELECT 'St Pancras' AS [Name]
	UNION SELECT 'St Pauls' AS [Name]
	UNION SELECT 'St Peter & St Paul' AS [Name]
	UNION SELECT 'St Peters Chailey' AS [Name]
	UNION SELECT 'St Philips' AS [Name]
	UNION SELECT 'St Thomas A Becket Jnr' AS [Name]
	UNION SELECT 'St Thomas' AS [Name]
	UNION SELECT 'Stafford Jnr' AS [Name]
	UNION SELECT 'Staffordshire County Council' AS [Name]
	UNION SELECT 'Staffordshire Police (Expired)' AS [Name]
	UNION SELECT 'Stanwell School' AS [Name]
	UNION SELECT 'Staplecross' AS [Name]
	UNION SELECT 'Stockton-on-Tees Borough Council' AS [Name]
	UNION SELECT 'Stone Cross' AS [Name]
	UNION SELECT 'Stonegate' AS [Name]
	UNION SELECT 'Suffolk County Council' AS [Name]
	UNION SELECT 'Surrey County Council' AS [Name]
	UNION SELECT 'Telscombe' AS [Name]
	UNION SELECT 'Test School' AS [Name]
	UNION SELECT 'The Haven' AS [Name]
	UNION SELECT 'Ticehurst & Flimwell' AS [Name]
	UNION SELECT 'To Be Confirmed' AS [Name]
	UNION SELECT 'Tollgate' AS [Name]
	UNION SELECT 'TTC 2000' AS [Name]
	UNION SELECT 'UK Road Safety Limited' AS [Name]
	UNION SELECT 'Wadhurst' AS [Name]
	UNION SELECT 'Wallands' AS [Name]
	UNION SELECT 'Warwickshire County Council' AS [Name]
	UNION SELECT 'West Midlands Driver Improvement Group' AS [Name]
	UNION SELECT 'West Rise Jnr' AS [Name]
	UNION SELECT 'West St Leonards' AS [Name]
	UNION SELECT 'Western Power Distribution' AS [Name]
	UNION SELECT 'Western Road' AS [Name]
	UNION SELECT 'Westfield' AS [Name]
	UNION SELECT 'White House' AS [Name]
	UNION SELECT 'William Parker' AS [Name]
	UNION SELECT 'Willingdon Primary' AS [Name]
	UNION SELECT 'Wiltshire County Council' AS [Name]
	UNION SELECT 'Wiltshire Police' AS [Name]
	UNION SELECT 'Wivelsfield' AS [Name]
	UNION SELECT 'Worcestershire County Council' AS [Name]
	) D
INNER JOIN Organisation O ON O.[Name] = D.[Name];