
		-- Country List
		/*
			Drop the View if it already exists
		*/
		IF OBJECT_ID('dbo.vwCountry', 'V') IS NOT NULL
		BEGIN
			DROP VIEW dbo.vwCountry;
		END		
		GO

		/*
			Create vwCountry
		*/
		CREATE VIEW vwCountry
		AS	
			SELECT 'Afghanistan' AS Name, 'AF' AS Alpha2Code, 'AFG' AS Alpha3Code, '4' AS UN_M49NumericalCode
			UNION SELECT 'Aland Islands', 'AX', 'ALA', '248'
			UNION SELECT 'Albania', 'AL', 'ALB', '8'
			UNION SELECT 'Algeria', 'DZ', 'DZA', '12'
			UNION SELECT 'American Samoa', 'AS', 'ASM', '16'
			UNION SELECT 'Andorra', 'AD', 'AND', '20'
			UNION SELECT 'Angola', 'AO', 'AGO', '24'
			UNION SELECT 'Anguilla', 'AI', 'AIA', '660'
			UNION SELECT 'Antarctica', 'AQ', 'ATA', '10'
			UNION SELECT 'Antigua and Barbuda', 'AG', 'ATG', '28'
			UNION SELECT 'Argentina', 'AR', 'ARG', '32'
			UNION SELECT 'Armenia', 'AM', 'ARM', '51'
			UNION SELECT 'Aruba', 'AW', 'ABW', '533'
			UNION SELECT 'Australia', 'AU', 'AUS', '36'
			UNION SELECT 'Austria', 'AT', 'AUT', '40'
			UNION SELECT 'Azerbaijan', 'AZ', 'AZE', '31'
			UNION SELECT 'Bahamas', 'BS', 'BHS', '44'
			UNION SELECT 'Bahrain', 'BH', 'BHR', '48'
			UNION SELECT 'Bangladesh', 'BD', 'BGD', '50'
			UNION SELECT 'Barbados', 'BB', 'BRB', '52'
			UNION SELECT 'Belarus', 'BY', 'BLR', '112'
			UNION SELECT 'Belgium', 'BE', 'BEL', '56'
			UNION SELECT 'Belize', 'BZ', 'BLZ', '84'
			UNION SELECT 'Benin', 'BJ', 'BEN', '204'
			UNION SELECT 'Bermuda', 'BM', 'BMU', '60'
			UNION SELECT 'Bhutan', 'BT', 'BTN', '64'
			UNION SELECT 'Bolivia', 'BO', 'BOL', '68'
			UNION SELECT 'Bosnia and Herzegovina', 'BA', 'BIH', '70'
			UNION SELECT 'Botswana', 'BW', 'BWA', '72'
			UNION SELECT 'Bouvet Island', 'BV', 'BVT', '74'
			UNION SELECT 'Brazil', 'BR', 'BRA', '76'
			UNION SELECT 'British Virgin Islands', 'VG', 'VGB', '92'
			UNION SELECT 'British Indian Ocean Territory', 'IO', 'IOT', '86'
			UNION SELECT 'Brunei Darussalam', 'BN', 'BRN', '96'
			UNION SELECT 'Bulgaria', 'BG', 'BGR', '100'
			UNION SELECT 'Burkina Faso', 'BF', 'BFA', '854'
			UNION SELECT 'Burundi', 'BI', 'BDI', '108'
			UNION SELECT 'Cambodia', 'KH', 'KHM', '116'
			UNION SELECT 'Cameroon', 'CM', 'CMR', '120'
			UNION SELECT 'Canada', 'CA', 'CAN', '124'
			UNION SELECT 'Cape Verde', 'CV', 'CPV', '132'
			UNION SELECT 'Cayman Islands', 'KY', 'CYM', '136'
			UNION SELECT 'Central African Republic', 'CF', 'CAF', '140'
			UNION SELECT 'Chad', 'TD', 'TCD', '148'
			UNION SELECT 'Chile', 'CL', 'CHL', '152'
			UNION SELECT 'China', 'CN', 'CHN', '156'
			UNION SELECT 'Hong Kong Special Administrative Region of China', 'HK', 'HKG', '344'
			UNION SELECT 'Macao Special Administrative Region of China', 'MO', 'MAC', '446'
			UNION SELECT 'Christmas Island', 'CX', 'CXR', '162'
			UNION SELECT 'Cocos (Keeling) Islands', 'CC', 'CCK', '166'
			UNION SELECT 'Colombia', 'CO', 'COL', '170'
			UNION SELECT 'Comoros', 'KM', 'COM', '174'
			UNION SELECT 'Congo (Brazzaville)', 'CG', 'COG', '178'
			UNION SELECT 'Congo Democratic Republic of the', 'CD', 'COD', '180'
			UNION SELECT 'Cook Islands', 'CK', 'COK', '184'
			UNION SELECT 'Costa Rica', 'CR', 'CRI', '188'
			UNION SELECT 'Côte d''Ivoire', 'CI', 'CIV', '384'
			UNION SELECT 'Croatia', 'HR', 'HRV', '191'
			UNION SELECT 'Cuba', 'CU', 'CUB', '192'
			UNION SELECT 'Cyprus', 'CY', 'CYP', '196'
			UNION SELECT 'Czech Republic', 'CZ', 'CZE', '203'
			UNION SELECT 'Denmark', 'DK', 'DNK', '208'
			UNION SELECT 'Djibouti', 'DJ', 'DJI', '262'
			UNION SELECT 'Dominica', 'DM', 'DMA', '212'
			UNION SELECT 'Dominican Republic', 'DO', 'DOM', '214'
			UNION SELECT 'Ecuador', 'EC', 'ECU', '218'
			UNION SELECT 'Egypt', 'EG', 'EGY', '818'
			UNION SELECT 'El Salvador', 'SV', 'SLV', '222'
			UNION SELECT 'Equatorial Guinea', 'GQ', 'GNQ', '226'
			UNION SELECT 'Eritrea', 'ER', 'ERI', '232'
			UNION SELECT 'Estonia', 'EE', 'EST', '233'
			UNION SELECT 'Ethiopia', 'ET', 'ETH', '231'
			UNION SELECT 'Falkland Islands (Malvinas)', 'FK', 'FLK', '238'
			UNION SELECT 'Faroe Islands', 'FO', 'FRO', '234'
			UNION SELECT 'Fiji', 'FJ', 'FJI', '242'
			UNION SELECT 'Finland', 'FI', 'FIN', '246'
			UNION SELECT 'France', 'FR', 'FRA', '250'
			UNION SELECT 'French Guiana', 'GF', 'GUF', '254'
			UNION SELECT 'French Polynesia', 'PF', 'PYF', '258'
			UNION SELECT 'French Southern Territories', 'TF', 'ATF', '260'
			UNION SELECT 'Gabon', 'GA', 'GAB', '266'
			UNION SELECT 'Gambia', 'GM', 'GMB', '270'
			UNION SELECT 'Georgia', 'GE', 'GEO', '268'
			UNION SELECT 'Germany', 'DE', 'DEU', '276'
			UNION SELECT 'Ghana', 'GH', 'GHA', '288'
			UNION SELECT 'Gibraltar', 'GI', 'GIB', '292'
			UNION SELECT 'Greece', 'GR', 'GRC', '300'
			UNION SELECT 'Greenland', 'GL', 'GRL', '304'
			UNION SELECT 'Grenada', 'GD', 'GRD', '308'
			UNION SELECT 'Guadeloupe', 'GP', 'GLP', '312'
			UNION SELECT 'Guam', 'GU', 'GUM', '316'
			UNION SELECT 'Guatemala', 'GT', 'GTM', '320'
			UNION SELECT 'Guernsey', 'GG', 'GGY', '831'
			UNION SELECT 'Guinea', 'GN', 'GIN', '324'
			UNION SELECT 'Guinea-Bissau', 'GW', 'GNB', '624'
			UNION SELECT 'Guyana', 'GY', 'GUY', '328'
			UNION SELECT 'Haiti', 'HT', 'HTI', '332'
			UNION SELECT 'Heard Island and Mcdonald Islands', 'HM', 'HMD', '334'
			UNION SELECT 'Holy See (Vatican City State)', 'VA', 'VAT', '336'
			UNION SELECT 'Honduras', 'HN', 'HND', '340'
			UNION SELECT 'Hungary', 'HU', 'HUN', '348'
			UNION SELECT 'Iceland', 'IS', 'ISL', '352'
			UNION SELECT 'India', 'IN', 'IND', '356'
			UNION SELECT 'Indonesia', 'ID', 'IDN', '360'
			UNION SELECT 'Iran Islamic Republic of', 'IR', 'IRN', '364'
			UNION SELECT 'Iraq', 'IQ', 'IRQ', '368'
			UNION SELECT 'Ireland', 'IE', 'IRL', '372'
			UNION SELECT 'Isle of Man', 'IM', 'IMN', '833'
			UNION SELECT 'Israel', 'IL', 'ISR', '376'
			UNION SELECT 'Italy', 'IT', 'ITA', '380'
			UNION SELECT 'Jamaica', 'JM', 'JAM', '388'
			UNION SELECT 'Japan', 'JP', 'JPN', '392'
			UNION SELECT 'Jersey', 'JE', 'JEY', '832'
			UNION SELECT 'Jordan', 'JO', 'JOR', '400'
			UNION SELECT 'Kazakhstan', 'KZ', 'KAZ', '398'
			UNION SELECT 'Kenya', 'KE', 'KEN', '404'
			UNION SELECT 'Kiribati', 'KI', 'KIR', '296'
			UNION SELECT 'Korea Democratic People''s Republic of', 'KP', 'PRK', '408'
			UNION SELECT 'Korea Republic of', 'KR', 'KOR', '410'
			UNION SELECT 'Kuwait', 'KW', 'KWT', '414'
			UNION SELECT 'Kyrgyzstan', 'KG', 'KGZ', '417'
			UNION SELECT 'Lao PDR', 'LA', 'LAO', '418'
			UNION SELECT 'Latvia', 'LV', 'LVA', '428'
			UNION SELECT 'Lebanon', 'LB', 'LBN', '422'
			UNION SELECT 'Lesotho', 'LS', 'LSO', '426'
			UNION SELECT 'Liberia', 'LR', 'LBR', '430'
			UNION SELECT 'Libya', 'LY', 'LBY', '434'
			UNION SELECT 'Liechtenstein', 'LI', 'LIE', '438'
			UNION SELECT 'Lithuania', 'LT', 'LTU', '440'
			UNION SELECT 'Luxembourg', 'LU', 'LUX', '442'
			UNION SELECT 'Macedonia Republic of', 'MK', 'MKD', '807'
			UNION SELECT 'Madagascar', 'MG', 'MDG', '450'
			UNION SELECT 'Malawi', 'MW', 'MWI', '454'
			UNION SELECT 'Malaysia', 'MY', 'MYS', '458'
			UNION SELECT 'Maldives', 'MV', 'MDV', '462'
			UNION SELECT 'Mali', 'ML', 'MLI', '466'
			UNION SELECT 'Malta', 'MT', 'MLT', '470'
			UNION SELECT 'Marshall Islands', 'MH', 'MHL', '584'
			UNION SELECT 'Martinique', 'MQ', 'MTQ', '474'
			UNION SELECT 'Mauritania', 'MR', 'MRT', '478'
			UNION SELECT 'Mauritius', 'MU', 'MUS', '480'
			UNION SELECT 'Mayotte', 'YT', 'MYT', '175'
			UNION SELECT 'Mexico', 'MX', 'MEX', '484'
			UNION SELECT 'Micronesia Federated States of', 'FM', 'FSM', '583'
			UNION SELECT 'Moldova', 'MD', 'MDA', '498'
			UNION SELECT 'Monaco', 'MC', 'MCO', '492'
			UNION SELECT 'Mongolia', 'MN', 'MNG', '496'
			UNION SELECT 'Montenegro', 'ME', 'MNE', '499'
			UNION SELECT 'Montserrat', 'MS', 'MSR', '500'
			UNION SELECT 'Morocco', 'MA', 'MAR', '504'
			UNION SELECT 'Mozambique', 'MZ', 'MOZ', '508'
			UNION SELECT 'Myanmar', 'MM', 'MMR', '104'
			UNION SELECT 'Namibia', 'NA', 'NAM', '516'
			UNION SELECT 'Nauru', 'NR', 'NRU', '520'
			UNION SELECT 'Nepal', 'NP', 'NPL', '524'
			UNION SELECT 'Netherlands', 'NL', 'NLD', '528'
			UNION SELECT 'Netherlands Antilles', 'AN', 'ANT', '530'
			UNION SELECT 'New Caledonia', 'NC', 'NCL', '540'
			UNION SELECT 'New Zealand', 'NZ', 'NZL', '554'
			UNION SELECT 'Nicaragua', 'NI', 'NIC', '558'
			UNION SELECT 'Niger', 'NE', 'NER', '562'
			UNION SELECT 'Nigeria', 'NG', 'NGA', '566'
			UNION SELECT 'Niue', 'NU', 'NIU', '570'
			UNION SELECT 'Norfolk Island', 'NF', 'NFK', '574'
			UNION SELECT 'Northern Mariana Islands', 'MP', 'MNP', '580'
			UNION SELECT 'Norway', 'NO', 'NOR', '578'
			UNION SELECT 'Oman', 'OM', 'OMN', '512'
			UNION SELECT 'Pakistan', 'PK', 'PAK', '586'
			UNION SELECT 'Palau', 'PW', 'PLW', '585'
			UNION SELECT 'Palestinian Territory Occupied', 'PS', 'PSE', '275'
			UNION SELECT 'Panama', 'PA', 'PAN', '591'
			UNION SELECT 'Papua New Guinea', 'PG', 'PNG', '598'
			UNION SELECT 'Paraguay', 'PY', 'PRY', '600'
			UNION SELECT 'Peru', 'PE', 'PER', '604'
			UNION SELECT 'Philippines', 'PH', 'PHL', '608'
			UNION SELECT 'Pitcairn', 'PN', 'PCN', '612'
			UNION SELECT 'Poland', 'PL', 'POL', '616'
			UNION SELECT 'Portugal', 'PT', 'PRT', '620'
			UNION SELECT 'Puerto Rico', 'PR', 'PRI', '630'
			UNION SELECT 'Qatar', 'QA', 'QAT', '634'
			UNION SELECT 'Réunion', 'RE', 'REU', '638'
			UNION SELECT 'Romania', 'RO', 'ROU', '642'
			UNION SELECT 'Russian Federation', 'RU', 'RUS', '643'
			UNION SELECT 'Rwanda', 'RW', 'RWA', '646'
			UNION SELECT 'Saint-Barthélemy', 'BL', 'BLM', '652'
			UNION SELECT 'Saint Helena', 'SH', 'SHN', '654'
			UNION SELECT 'Saint Kitts and Nevis', 'KN', 'KNA', '659'
			UNION SELECT 'Saint Lucia', 'LC', 'LCA', '662'
			UNION SELECT 'Saint-Martin (French part)', 'MF', 'MAF', '663'
			UNION SELECT 'Saint Pierre and Miquelon', 'PM', 'SPM', '666'
			UNION SELECT 'Saint Vincent and Grenadines', 'VC', 'VCT', '670'
			UNION SELECT 'Samoa', 'WS', 'WSM', '882'
			UNION SELECT 'San Marino', 'SM', 'SMR', '674'
			UNION SELECT 'Sao Tome and Principe', 'ST', 'STP', '678'
			UNION SELECT 'Saudi Arabia', 'SA', 'SAU', '682'
			UNION SELECT 'Senegal', 'SN', 'SEN', '686'
			UNION SELECT 'Serbia', 'RS', 'SRB', '688'
			UNION SELECT 'Seychelles', 'SC', 'SYC', '690'
			UNION SELECT 'Sierra Leone', 'SL', 'SLE', '694'
			UNION SELECT 'Singapore', 'SG', 'SGP', '702'
			UNION SELECT 'Slovakia', 'SK', 'SVK', '703'
			UNION SELECT 'Slovenia', 'SI', 'SVN', '705'
			UNION SELECT 'Solomon Islands', 'SB', 'SLB', '90'
			UNION SELECT 'Somalia', 'SO', 'SOM', '706'
			UNION SELECT 'South Africa', 'ZA', 'ZAF', '710'
			UNION SELECT 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', '239'
			UNION SELECT 'South Sudan', 'SS', 'SSD', '728'
			UNION SELECT 'Spain', 'ES', 'ESP', '724'
			UNION SELECT 'Sri Lanka', 'LK', 'LKA', '144'
			UNION SELECT 'Sudan', 'SD', 'SDN', '736'
			UNION SELECT 'Suriname *', 'SR', 'SUR', '740'
			UNION SELECT 'Svalbard and Jan Mayen Islands', 'SJ', 'SJM', '744'
			UNION SELECT 'Swaziland', 'SZ', 'SWZ', '748'
			UNION SELECT 'Sweden', 'SE', 'SWE', '752'
			UNION SELECT 'Switzerland', 'CH', 'CHE', '756'
			UNION SELECT 'Syrian Arab Republic (Syria)', 'SY', 'SYR', '760'
			UNION SELECT 'Taiwan Republic of China', 'TW', 'TWN', '158'
			UNION SELECT 'Tajikistan', 'TJ', 'TJK', '762'
			UNION SELECT 'Tanzania * United Republic of', 'TZ', 'TZA', '834'
			UNION SELECT 'Thailand', 'TH', 'THA', '764'
			UNION SELECT 'Timor-Leste', 'TL', 'TLS', '626'
			UNION SELECT 'Togo', 'TG', 'TGO', '768'
			UNION SELECT 'Tokelau', 'TK', 'TKL', '772'
			UNION SELECT 'Tonga', 'TO', 'TON', '776'
			UNION SELECT 'Trinidad and Tobago', 'TT', 'TTO', '780'
			UNION SELECT 'Tunisia', 'TN', 'TUN', '788'
			UNION SELECT 'Turkey', 'TR', 'TUR', '792'
			UNION SELECT 'Turkmenistan', 'TM', 'TKM', '795'
			UNION SELECT 'Turks and Caicos Islands', 'TC', 'TCA', '796'
			UNION SELECT 'Tuvalu', 'TV', 'TUV', '798'
			UNION SELECT 'Uganda', 'UG', 'UGA', '800'
			UNION SELECT 'Ukraine', 'UA', 'UKR', '804'
			UNION SELECT 'United Arab Emirates', 'AE', 'ARE', '784'
			UNION SELECT 'United Kingdom', 'GB', 'GBR', '826'
			UNION SELECT 'United States of America', 'US', 'USA', '840'
			UNION SELECT 'United States Minor Outlying Islands', 'UM', 'UMI', '581'
			UNION SELECT 'Uruguay', 'UY', 'URY', '858'
			UNION SELECT 'Uzbekistan', 'UZ', 'UZB', '860'
			UNION SELECT 'Vanuatu', 'VU', 'VUT', '548'
			UNION SELECT 'Venezuela (Bolivarian Republic of)', 'VE', 'VEN', '862'
			UNION SELECT 'Viet Nam', 'VN', 'VNM', '704'
			UNION SELECT 'Virgin Islands US', 'VI', 'VIR', '850'
			UNION SELECT 'Wallis and Futuna Islands', 'WF', 'WLF', '876'
			UNION SELECT 'Western Sahara', 'EH', 'ESH', '732'
			UNION SELECT 'Yemen', 'YE', 'YEM', '887'
			UNION SELECT 'Zambia', 'ZM', 'ZMB', '894'
			UNION SELECT 'Zimbabwe', 'ZW', 'ZWE', '716'
			;

		GO
		
		/*********************************************************************************************************************/
		