//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdministrationMenuGroupItem
    {
        public int Id { get; set; }
        public int AdminMenuGroupId { get; set; }
        public int AdminMenuItemId { get; set; }
        public Nullable<int> SortNumber { get; set; }
    
        public virtual AdministrationMenuItem AdministrationMenuItem { get; set; }
        public virtual AdministrationMenuGroup AdministrationMenuGroup { get; set; }
    }
}
