//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllCourseTypeDocument
    {
        public int Id { get; set; }
        public int CourseTypeId { get; set; }
        public int DocumentId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public int AddByUserId { get; set; }
    
        public virtual CourseType CourseType { get; set; }
        public virtual Document Document { get; set; }
        public virtual User User { get; set; }
    }
}
