//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivedSM
    {
        public int Id { get; set; }
        public Nullable<int> ScheduledSMSId { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> ScheduledSMSStateId { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<bool> ASAP { get; set; }
        public Nullable<System.DateTime> SendAfterDate { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public Nullable<System.DateTime> DateArchived { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual ScheduledSMSState ScheduledSMSState { get; set; }
    }
}
