//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelledRefund
    {
        public int Id { get; set; }
        public int RefundId { get; set; }
        public System.DateTime DateCancelled { get; set; }
        public int CancelledByUserId { get; set; }
    
        public virtual Refund Refund { get; set; }
        public virtual User User { get; set; }
    }
}
