//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientOnlineBookingState
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<bool> DetailsRecorded { get; set; }
        public Nullable<int> DORSSchemeId { get; set; }
        public Nullable<bool> AvailableForDORSScheme { get; set; }
        public Nullable<bool> ConfirmedName { get; set; }
        public Nullable<bool> ConfirmedCourseAttendance { get; set; }
        public Nullable<bool> ConfirmedWillPayCourseSupplier { get; set; }
        public Nullable<bool> CompletedSpecialRequirements { get; set; }
        public Nullable<bool> CourseBooked { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<System.DateTime> DateTimeCourseBooked { get; set; }
        public Nullable<bool> AgreedToTermsAndConditions { get; set; }
        public Nullable<System.DateTime> DateTimeAgreedToTermsAndConditions { get; set; }
        public Nullable<bool> FullPaymentRecieved { get; set; }
        public Nullable<System.DateTime> DateTimePaymentRecieved { get; set; }
        public Nullable<bool> EmailConfirmationSent { get; set; }
        public Nullable<System.DateTime> DateTimeEmailSent { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual DORSScheme DORSScheme { get; set; }
        public virtual Client Client { get; set; }
    }
}
