//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientChangeLog
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string ChangeType { get; set; }
        public string ColumnName { get; set; }
        public string PreviousValue { get; set; }
        public string NewValue { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> AssociatedUserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
