//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientOnlineEmailChangeRequestHistory
    {
        public int Id { get; set; }
        public System.DateTime DateRequested { get; set; }
        public int RequestedByUserId { get; set; }
        public int ClientId { get; set; }
        public int ClientOrganisationId { get; set; }
        public string NewEmailAddress { get; set; }
        public string PreviousEmailAddress { get; set; }
        public string ClientName { get; set; }
        public string ConfirmationCode { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
    
        public virtual ClientOrganisation ClientOrganisation { get; set; }
        public virtual User User { get; set; }
        public virtual Client Client { get; set; }
    }
}
