//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPreviousId
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int PreviousClientId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> PreviousOrgId { get; set; }
        public Nullable<int> PreviousReferrerOrgId { get; set; }
        public Nullable<int> PreviousReferrerRgnId { get; set; }
        public Nullable<int> PreviousProviderRgnId { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
