//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseType
    {
        public CourseType()
        {
            this.VenueCourseType = new HashSet<VenueCourseType>();
            this.Course = new HashSet<Course>();
            this.TrainerCourseType = new HashSet<TrainerCourseType>();
            this.CourseTypeCategories = new HashSet<CourseTypeCategory>();
            this.AllCourseTypeDocuments = new HashSet<AllCourseTypeDocument>();
            this.CourseTypeTolerances = new HashSet<CourseTypeTolerance>();
            this.CourseStencils = new HashSet<CourseStencil>();
            this.CourseCloneRequests = new HashSet<CourseCloneRequest>();
            this.DORSSchemeCourseTypes = new HashSet<DORSSchemeCourseType>();
            this.CourseTypeCategoryFees = new HashSet<CourseTypeCategoryFee>();
            this.CourseTypeCategoryRebookingFees = new HashSet<CourseTypeCategoryRebookingFee>();
            this.CourseTypeFees = new HashSet<CourseTypeFee>();
            this.CourseTypeRebookingFees = new HashSet<CourseTypeRebookingFee>();
            this.OrganisationContactCourseTypes = new HashSet<OrganisationContactCourseType>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int OrganisationId { get; set; }
        public bool Disabled { get; set; }
        public Nullable<bool> DORSOnly { get; set; }
        public int DaysBeforeCourseLastBooking { get; set; }
        public int MinTheoryTrainers { get; set; }
        public int MinPracticalTrainers { get; set; }
        public int MaxTheoryTrainers { get; set; }
        public int MaxPracticalTrainers { get; set; }
        public int MaxPlaces { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual ICollection<VenueCourseType> VenueCourseType { get; set; }
        public virtual ICollection<Course> Course { get; set; }
        public virtual ICollection<TrainerCourseType> TrainerCourseType { get; set; }
        public virtual ICollection<CourseTypeCategory> CourseTypeCategories { get; set; }
        public virtual ICollection<AllCourseTypeDocument> AllCourseTypeDocuments { get; set; }
        public virtual ICollection<CourseTypeTolerance> CourseTypeTolerances { get; set; }
        public virtual ICollection<CourseStencil> CourseStencils { get; set; }
        public virtual ICollection<CourseCloneRequest> CourseCloneRequests { get; set; }
        public virtual ICollection<DORSSchemeCourseType> DORSSchemeCourseTypes { get; set; }
        public virtual ICollection<CourseTypeCategoryFee> CourseTypeCategoryFees { get; set; }
        public virtual ICollection<CourseTypeCategoryRebookingFee> CourseTypeCategoryRebookingFees { get; set; }
        public virtual ICollection<CourseTypeFee> CourseTypeFees { get; set; }
        public virtual ICollection<CourseTypeRebookingFee> CourseTypeRebookingFees { get; set; }
        public virtual ICollection<OrganisationContactCourseType> OrganisationContactCourseTypes { get; set; }
    }
}
