//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseLog
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public int CreatedByUserId { get; set; }
        public string Item { get; set; }
        public string NewValue { get; set; }
        public string OldValue { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
