//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTrainer
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public int TrainerId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<bool> AttendanceCheckRequired { get; set; }
        public Nullable<System.DateTime> AttendanceLastUpdated { get; set; }
        public Nullable<int> BookedForSessionNumber { get; set; }
        public bool BookedForTheory { get; set; }
        public bool BookedForPractical { get; set; }
        public string Reference { get; set; }
        public Nullable<decimal> PaymentDue { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<int> CourseDateId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Trainer Trainer { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual TrainingSession TrainingSession { get; set; }
        public virtual CourseDate CourseDate { get; set; }
    }
}
