//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDocumentRequest
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public System.DateTime DateRequested { get; set; }
        public int RequestedByUserId { get; set; }
        public int CourseDocumentRequestTypeId { get; set; }
        public bool RequestCompleted { get; set; }
        public Nullable<System.DateTime> DateRequestCompleted { get; set; }
        public string Description { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual CourseDocumentRequestType CourseDocumentRequestType { get; set; }
        public virtual User User { get; set; }
    }
}
