//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseClientRemoved
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime DateRemoved { get; set; }
        public int RemovedByUserId { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> DORSOfferWithdrawn { get; set; }
        public System.DateTime DateAddedToCourse { get; set; }
        public int CourseClientId { get; set; }
        public bool PartOfDorsCourseTransfer { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Course Course { get; set; }
        public virtual CourseClient CourseClient { get; set; }
        public virtual User User { get; set; }
    }
}
