//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseClientTransferRequest
    {
        public int Id { get; set; }
        public int RequestedByClientId { get; set; }
        public System.DateTime DateTimeRequested { get; set; }
        public int TransferFromCourseId { get; set; }
        public int TransferToCourseId { get; set; }
        public Nullable<decimal> RebookingFeeAmount { get; set; }
        public bool ToCourseBooked { get; set; }
        public bool FromCourseUnbooked { get; set; }
        public bool TransferRequestRejected { get; set; }
        public bool RejectNotified { get; set; }
        public string RejectionReason { get; set; }
        public bool TransferRequestAccepted { get; set; }
        public bool ClientNotified { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Course Course1 { get; set; }
        public virtual Client Client { get; set; }
    }
}
