//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseGroupEmailRequest
    {
        public CourseGroupEmailRequest()
        {
            this.CourseGroupEmailRequestAttachments = new HashSet<CourseGroupEmailRequestAttachment>();
        }
    
        public int Id { get; set; }
        public int CourseId { get; set; }
        public System.DateTime DateRequested { get; set; }
        public int RequestedByUserId { get; set; }
        public bool SendAllClients { get; set; }
        public bool SendAllTrainers { get; set; }
        public bool SeparateEmails { get; set; }
        public bool OneEmailWithHiddenAddresses { get; set; }
        public string CCEmailAddresses { get; set; }
        public string BCCEmailAddresses { get; set; }
        public string Subject { get; set; }
        public bool StartDearNamed { get; set; }
        public bool StartDearSirMadam { get; set; }
        public bool StartToWhomItMayConcern { get; set; }
        public string Content { get; set; }
        public bool SendASAP { get; set; }
        public Nullable<System.DateTime> SendAfterDateTime { get; set; }
        public bool EmailsValidatedAndCreated { get; set; }
        public Nullable<System.DateTime> DateEmailsValidatedAndCreated { get; set; }
        public bool RequestRejected { get; set; }
        public string RejectionReason { get; set; }
        public bool ReadyToSend { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<CourseGroupEmailRequestAttachment> CourseGroupEmailRequestAttachments { get; set; }
        public virtual User User { get; set; }
    }
}
