//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseReferenceGenerator
    {
        public CourseReferenceGenerator()
        {
            this.OrganisationSelfConfigurations = new HashSet<OrganisationSelfConfiguration>();
            this.CourseStencils = new HashSet<CourseStencil>();
            this.CourseCloneRequests = new HashSet<CourseCloneRequest>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<OrganisationSelfConfiguration> OrganisationSelfConfigurations { get; set; }
        public virtual ICollection<CourseStencil> CourseStencils { get; set; }
        public virtual ICollection<CourseCloneRequest> CourseCloneRequests { get; set; }
    }
}
