//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseCloneRequest
    {
        public CourseCloneRequest()
        {
            this.CourseClonedCourses = new HashSet<CourseClonedCourse>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> CourseTypeId { get; set; }
        public Nullable<int> CourseTypeCategoryId { get; set; }
        public Nullable<int> RequestedByUserId { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CourseReferenceGeneratorId { get; set; }
        public Nullable<bool> UseSameReference { get; set; }
        public Nullable<bool> UseSameTrainers { get; set; }
        public Nullable<int> MaxCourses { get; set; }
        public Nullable<bool> WeeklyCourses { get; set; }
        public Nullable<bool> MonthlyCourses { get; set; }
        public Nullable<int> EveryNWeeks { get; set; }
        public Nullable<int> EveryNMonths { get; set; }
        public Nullable<bool> NewCoursesCreated { get; set; }
        public Nullable<System.DateTime> DateNewCoursesCreated { get; set; }
        public Nullable<bool> ClonedCoursesRemoved { get; set; }
    
        public virtual ICollection<CourseClonedCourse> CourseClonedCourses { get; set; }
        public virtual CourseReferenceGenerator CourseReferenceGenerator { get; set; }
        public virtual CourseType CourseType { get; set; }
        public virtual CourseTypeCategory CourseTypeCategory { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual User User { get; set; }
    }
}
