//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseVenue
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public int VenueId { get; set; }
        public int MaximumPlaces { get; set; }
        public int ReservedPlaces { get; set; }
        public Nullable<int> VenueLocaleId { get; set; }
        public bool EmailAvailability { get; set; }
        public bool AvailabilityEmailed { get; set; }
        public Nullable<System.DateTime> DateAvailabilityEmailed { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Venue Venue { get; set; }
        public virtual VenueLocale VenueLocale { get; set; }
    }
}
