//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseNote = new HashSet<CourseNote>();
            this.CoursePreviousId = new HashSet<CoursePreviousId>();
            this.CourseDate = new HashSet<CourseDate>();
            this.CourseVenue = new HashSet<CourseVenue>();
            this.CourseSchedule = new HashSet<CourseSchedule>();
            this.CourseTrainer = new HashSet<CourseTrainer>();
            this.CourseLanguage = new HashSet<CourseLanguage>();
            this.CourseLog = new HashSet<CourseLog>();
            this.CourseClientPayments = new HashSet<CourseClientPayment>();
            this.CourseQuickSearches = new HashSet<CourseQuickSearch>();
            this.DORSAttendanceLogs = new HashSet<DORSAttendanceLog>();
            this.CourseDateClientAttendances = new HashSet<CourseDateClientAttendance>();
            this.CourseDateTrainerAttendances = new HashSet<CourseDateTrainerAttendance>();
            this.CourseDocuments = new HashSet<CourseDocument>();
            this.CourseDocumentTemplates = new HashSet<CourseDocumentTemplate>();
            this.ClientOnlineBookingStates = new HashSet<ClientOnlineBookingState>();
            this.CancelledCourses = new HashSet<CancelledCourse>();
            this.DORSCancelledCourses = new HashSet<DORSCancelledCourse>();
            this.DORSClientCourseRemovals = new HashSet<DORSClientCourseRemoval>();
            this.CourseClientTransferreds = new HashSet<CourseClientTransferred>();
            this.CourseClientTransferreds1 = new HashSet<CourseClientTransferred>();
            this.DORSClientCourseTransferreds = new HashSet<DORSClientCourseTransferred>();
            this.DORSClientCourseTransferreds1 = new HashSet<DORSClientCourseTransferred>();
            this.CourseOverBookingNotifications = new HashSet<CourseOverBookingNotification>();
            this.CourseClientEmailReminders = new HashSet<CourseClientEmailReminder>();
            this.CourseClientSMSReminders = new HashSet<CourseClientSMSReminder>();
            this.CourseStencilCourses = new HashSet<CourseStencilCourse>();
            this.CourseDORSForceContracts = new HashSet<CourseDORSForceContract>();
            this.CourseClonedCourses = new HashSet<CourseClonedCourse>();
            this.CourseDORSClients = new HashSet<CourseDORSClient>();
            this.DORSClientCourseAttendances = new HashSet<DORSClientCourseAttendance>();
            this.DORSCourses = new HashSet<DORSCourse>();
            this.CourseInterpreterLanguages = new HashSet<CourseInterpreterLanguage>();
            this.TrainerBookingRequests = new HashSet<TrainerBookingRequest>();
            this.CourseDORSNotifications = new HashSet<CourseDORSNotification>();
            this.CourseClientPaymentTransfers = new HashSet<CourseClientPaymentTransfer>();
            this.CourseClientPayments1 = new HashSet<CourseClientPayment>();
            this.CourseClientPaymentTransfers1 = new HashSet<CourseClientPaymentTransfer>();
            this.CourseDORSClients1 = new HashSet<CourseDORSClient>();
            this.CourseDORSClients2 = new HashSet<CourseDORSClient>();
            this.CourseClientTransferRequests = new HashSet<CourseClientTransferRequest>();
            this.CourseClientTransferRequests1 = new HashSet<CourseClientTransferRequest>();
            this.CourseVenueEmails = new HashSet<CourseVenueEmail>();
            this.CourseGroupEmailRequests = new HashSet<CourseGroupEmailRequest>();
            this.CourseSessionAllocations = new HashSet<CourseSessionAllocation>();
            this.CourseDocumentRequests = new HashSet<CourseDocumentRequest>();
            this.NetcallOverrides = new HashSet<NetcallOverride>();
            this.CourseInterpreters = new HashSet<CourseInterpreter>();
            this.RefundRequests = new HashSet<RefundRequest>();
            this.TaskRelatedToCourses = new HashSet<TaskRelatedToCourse>();
            this.CourseLockeds = new HashSet<CourseLocked>();
            this.CourseProfileUneditables = new HashSet<CourseProfileUneditable>();
            this.CourseClients = new HashSet<CourseClient>();
            this.CourseClientRemoveds = new HashSet<CourseClientRemoved>();
            this.OrganisationCourses = new HashSet<OrganisationCourse>();
            this.PaymentErrorInformations = new HashSet<PaymentErrorInformation>();
        }
    
        public int Id { get; set; }
        public int CourseTypeId { get; set; }
        public string DefaultStartTime { get; set; }
        public string DefaultEndTime { get; set; }
        public Nullable<bool> Available { get; set; }
        public int OrganisationId { get; set; }
        public string Reference { get; set; }
        public Nullable<int> TrainersRequired { get; set; }
        public Nullable<bool> SendAttendanceDORS { get; set; }
        public Nullable<bool> TrainerUpdatedAttendance { get; set; }
        public Nullable<bool> ManualCarsOnly { get; set; }
        public Nullable<bool> OnlineManualCarsOnly { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> CourseTypeCategoryId { get; set; }
        public Nullable<System.DateTime> LastBookingDate { get; set; }
        public Nullable<bool> AttendanceCheckRequired { get; set; }
        public Nullable<System.DateTime> DateAttendanceSentToDORS { get; set; }
        public Nullable<bool> AttendanceSentToDORS { get; set; }
        public Nullable<bool> AttendanceCheckVerified { get; set; }
        public Nullable<bool> DORSCourse { get; set; }
        public Nullable<bool> DORSNotificationRequested { get; set; }
        public Nullable<bool> DORSNotified { get; set; }
        public Nullable<System.DateTime> DateDORSNotified { get; set; }
        public Nullable<bool> HasInterpreter { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public string DORSNotificationReason { get; set; }
        public Nullable<bool> PracticalCourse { get; set; }
        public Nullable<bool> TheoryCourse { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CourseRegisterDocumentId { get; set; }
        public Nullable<int> CourseAttendanceSignInDocumentId { get; set; }
    
        public virtual CourseType CourseType { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual ICollection<CourseNote> CourseNote { get; set; }
        public virtual ICollection<CoursePreviousId> CoursePreviousId { get; set; }
        public virtual ICollection<CourseDate> CourseDate { get; set; }
        public virtual ICollection<CourseVenue> CourseVenue { get; set; }
        public virtual ICollection<CourseSchedule> CourseSchedule { get; set; }
        public virtual ICollection<CourseTrainer> CourseTrainer { get; set; }
        public virtual ICollection<CourseLanguage> CourseLanguage { get; set; }
        public virtual ICollection<CourseLog> CourseLog { get; set; }
        public virtual ICollection<CourseClientPayment> CourseClientPayments { get; set; }
        public virtual CourseTypeCategory CourseTypeCategory { get; set; }
        public virtual ICollection<CourseQuickSearch> CourseQuickSearches { get; set; }
        public virtual ICollection<DORSAttendanceLog> DORSAttendanceLogs { get; set; }
        public virtual ICollection<CourseDateClientAttendance> CourseDateClientAttendances { get; set; }
        public virtual ICollection<CourseDateTrainerAttendance> CourseDateTrainerAttendances { get; set; }
        public virtual ICollection<CourseDocument> CourseDocuments { get; set; }
        public virtual ICollection<CourseDocumentTemplate> CourseDocumentTemplates { get; set; }
        public virtual ICollection<ClientOnlineBookingState> ClientOnlineBookingStates { get; set; }
        public virtual ICollection<CancelledCourse> CancelledCourses { get; set; }
        public virtual ICollection<DORSCancelledCourse> DORSCancelledCourses { get; set; }
        public virtual ICollection<DORSClientCourseRemoval> DORSClientCourseRemovals { get; set; }
        public virtual ICollection<CourseClientTransferred> CourseClientTransferreds { get; set; }
        public virtual ICollection<CourseClientTransferred> CourseClientTransferreds1 { get; set; }
        public virtual ICollection<DORSClientCourseTransferred> DORSClientCourseTransferreds { get; set; }
        public virtual ICollection<DORSClientCourseTransferred> DORSClientCourseTransferreds1 { get; set; }
        public virtual ICollection<CourseOverBookingNotification> CourseOverBookingNotifications { get; set; }
        public virtual ICollection<CourseClientEmailReminder> CourseClientEmailReminders { get; set; }
        public virtual ICollection<CourseClientSMSReminder> CourseClientSMSReminders { get; set; }
        public virtual ICollection<CourseStencilCourse> CourseStencilCourses { get; set; }
        public virtual ICollection<CourseDORSForceContract> CourseDORSForceContracts { get; set; }
        public virtual ICollection<CourseClonedCourse> CourseClonedCourses { get; set; }
        public virtual ICollection<CourseDORSClient> CourseDORSClients { get; set; }
        public virtual ICollection<DORSClientCourseAttendance> DORSClientCourseAttendances { get; set; }
        public virtual ICollection<DORSCourse> DORSCourses { get; set; }
        public virtual ICollection<CourseInterpreterLanguage> CourseInterpreterLanguages { get; set; }
        public virtual ICollection<TrainerBookingRequest> TrainerBookingRequests { get; set; }
        public virtual ICollection<CourseDORSNotification> CourseDORSNotifications { get; set; }
        public virtual ICollection<CourseClientPaymentTransfer> CourseClientPaymentTransfers { get; set; }
        public virtual ICollection<CourseClientPayment> CourseClientPayments1 { get; set; }
        public virtual ICollection<CourseClientPaymentTransfer> CourseClientPaymentTransfers1 { get; set; }
        public virtual ICollection<CourseDORSClient> CourseDORSClients1 { get; set; }
        public virtual ICollection<CourseDORSClient> CourseDORSClients2 { get; set; }
        public virtual ICollection<CourseClientTransferRequest> CourseClientTransferRequests { get; set; }
        public virtual ICollection<CourseClientTransferRequest> CourseClientTransferRequests1 { get; set; }
        public virtual ICollection<CourseVenueEmail> CourseVenueEmails { get; set; }
        public virtual ICollection<CourseGroupEmailRequest> CourseGroupEmailRequests { get; set; }
        public virtual ICollection<CourseSessionAllocation> CourseSessionAllocations { get; set; }
        public virtual ICollection<CourseDocumentRequest> CourseDocumentRequests { get; set; }
        public virtual ICollection<NetcallOverride> NetcallOverrides { get; set; }
        public virtual ICollection<CourseInterpreter> CourseInterpreters { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<RefundRequest> RefundRequests { get; set; }
        public virtual ICollection<TaskRelatedToCourse> TaskRelatedToCourses { get; set; }
        public virtual ICollection<CourseLocked> CourseLockeds { get; set; }
        public virtual ICollection<CourseProfileUneditable> CourseProfileUneditables { get; set; }
        public virtual ICollection<CourseClient> CourseClients { get; set; }
        public virtual ICollection<CourseClientRemoved> CourseClientRemoveds { get; set; }
        public virtual Document Document { get; set; }
        public virtual Document Document1 { get; set; }
        public virtual ICollection<OrganisationCourse> OrganisationCourses { get; set; }
        public virtual ICollection<PaymentErrorInformation> PaymentErrorInformations { get; set; }
    }
}
