//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseLanguage
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public int OrganisationLanguageId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual OrganisationLanguage OrganisationLanguage { get; set; }
    }
}
