//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseStencil
    {
        public CourseStencil()
        {
            this.CourseStencilCourses = new HashSet<CourseStencilCourse>();
            this.OrganisationCourseStencils = new HashSet<OrganisationCourseStencil>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> VersionNumber { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<int> MaxCourses { get; set; }
        public Nullable<bool> ExcludeBankHolidays { get; set; }
        public Nullable<bool> ExcludeWeekends { get; set; }
        public Nullable<System.DateTime> EarliestStartDate { get; set; }
        public Nullable<System.DateTime> LatestStartDate { get; set; }
        public string SessionStartTime1 { get; set; }
        public string SessionEndTime1 { get; set; }
        public string SessionStartTime2 { get; set; }
        public string SessionEndTime2 { get; set; }
        public string SessionStartTime3 { get; set; }
        public string SessionEndTime3 { get; set; }
        public Nullable<int> MultiDayCourseDaysBetween { get; set; }
        public Nullable<int> CourseTypeId { get; set; }
        public Nullable<int> CourseTypeCategoryId { get; set; }
        public Nullable<int> VenueId { get; set; }
        public Nullable<decimal> TrainerCost { get; set; }
        public Nullable<int> TrainersRequired { get; set; }
        public Nullable<int> CoursePlaces { get; set; }
        public Nullable<int> ReservedPlaces { get; set; }
        public Nullable<int> CourseReferenceGeneratorId { get; set; }
        public string BeginReferenceWith { get; set; }
        public string EndReferenceWith { get; set; }
        public Nullable<bool> WeeklyCourses { get; set; }
        public Nullable<int> WeeklyCourseStartDay { get; set; }
        public Nullable<bool> MonthlyCourses { get; set; }
        public Nullable<int> MonthlyCoursesPreferredDayStart { get; set; }
        public Nullable<bool> DailyCourses { get; set; }
        public Nullable<int> DailyCoursesSkipDays { get; set; }
        public Nullable<bool> ExcludeMonday { get; set; }
        public Nullable<bool> ExcludeTuesday { get; set; }
        public Nullable<bool> ExcludeWednesday { get; set; }
        public Nullable<bool> ExcludeThursday { get; set; }
        public Nullable<bool> ExcludeFriday { get; set; }
        public Nullable<bool> ExcludeSaturday { get; set; }
        public Nullable<bool> ExcludeSunday { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> CreateCourses { get; set; }
        public Nullable<bool> RemoveCourses { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> DateCoursesCreated { get; set; }
        public Nullable<System.DateTime> DateCoursesRemoved { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<int> CourseCreationInitiatedByUserId { get; set; }
        public Nullable<System.DateTime> DateCourseCreationInitiated { get; set; }
        public Nullable<int> CourseRemoveInitiatedByUserId { get; set; }
        public Nullable<System.DateTime> DateCourseRemoveInitiated { get; set; }
        public bool HasPracticalElement { get; set; }
        public bool HasTheoryElement { get; set; }
        public Nullable<int> PracticalDefaultSessionNumber { get; set; }
        public Nullable<int> TheoryDefaultSessionNumber { get; set; }
    
        public virtual CourseReferenceGenerator CourseReferenceGenerator { get; set; }
        public virtual CourseType CourseType { get; set; }
        public virtual CourseTypeCategory CourseTypeCategory { get; set; }
        public virtual Venue Venue { get; set; }
        public virtual ICollection<CourseStencilCourse> CourseStencilCourses { get; set; }
        public virtual ICollection<OrganisationCourseStencil> OrganisationCourseStencils { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
    }
}
