//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTypeTolerance
    {
        public int Id { get; set; }
        public int CourseTypeId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> FirstRatio { get; set; }
        public Nullable<int> SecondRatio { get; set; }
        public Nullable<int> MaximumAttendees { get; set; }
        public Nullable<int> Tolerance { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual CourseType CourseType { get; set; }
        public virtual User User { get; set; }
    }
}
