//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseVenueEmail
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public int VenueId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int ScheduledEmailId { get; set; }
        public int CourseVenueEmailReasonId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual CourseVenueEmailReason CourseVenueEmailReason { get; set; }
        public virtual ScheduledEmail ScheduledEmail { get; set; }
        public virtual Venue Venue { get; set; }
    }
}
