//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDORSForceContract
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public int DORSForceContractId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual DORSForceContract DORSForceContract { get; set; }
    }
}
