//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard
    {
        public Dashboard()
        {
            this.DashboardGroupItems = new HashSet<DashboardGroupItem>();
            this.DashboardReports = new HashSet<DashboardReport>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<int> DataViewId { get; set; }
        public string DashboardType { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<int> ShowLegend { get; set; }
        public Nullable<int> VersionNumber { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    
        public virtual ICollection<DashboardGroupItem> DashboardGroupItems { get; set; }
        public virtual ICollection<DashboardReport> DashboardReports { get; set; }
    }
}
