//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataViewColumn
    {
        public DataViewColumn()
        {
            this.DashboardColumns = new HashSet<DashboardColumn>();
            this.ReportChartColumns = new HashSet<ReportChartColumn>();
            this.ReportDataGridColumns = new HashSet<ReportDataGridColumn>();
            this.ReportParameters = new HashSet<ReportParameter>();
            this.DataViewForDocumentTemplateViewableColumns = new HashSet<DataViewForDocumentTemplateViewableColumn>();
            this.DocumentTemplateDataViewColumns = new HashSet<DocumentTemplateDataViewColumn>();
            this.EmailTemplateCategoryColumns = new HashSet<EmailTemplateCategoryColumn>();
            this.LetterCategoryColumns = new HashSet<LetterCategoryColumn>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DataViewId { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string DataType { get; set; }
        public Nullable<bool> Removed { get; set; }
    
        public virtual ICollection<DashboardColumn> DashboardColumns { get; set; }
        public virtual DataView DataView { get; set; }
        public virtual ICollection<ReportChartColumn> ReportChartColumns { get; set; }
        public virtual ICollection<ReportDataGridColumn> ReportDataGridColumns { get; set; }
        public virtual ICollection<ReportParameter> ReportParameters { get; set; }
        public virtual ICollection<DataViewForDocumentTemplateViewableColumn> DataViewForDocumentTemplateViewableColumns { get; set; }
        public virtual ICollection<DocumentTemplateDataViewColumn> DocumentTemplateDataViewColumns { get; set; }
        public virtual ICollection<EmailTemplateCategoryColumn> EmailTemplateCategoryColumns { get; set; }
        public virtual ICollection<LetterCategoryColumn> LetterCategoryColumns { get; set; }
    }
}
