//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataView
    {
        public DataView()
        {
            this.DataViewColumns = new HashSet<DataViewColumn>();
            this.ReportDataGrids = new HashSet<ReportDataGrid>();
            this.ReportCharts = new HashSet<ReportChart>();
            this.DataViewForDocumentTemplates = new HashSet<DataViewForDocumentTemplate>();
            this.DocumentTemplateDataViews = new HashSet<DocumentTemplateDataView>();
            this.DataViewLogs = new HashSet<DataViewLog>();
            this.EmailTemplateCategories = new HashSet<EmailTemplateCategory>();
            this.LetterCategories = new HashSet<LetterCategory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<int> AddedByUserId { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
    
        public virtual ICollection<DataViewColumn> DataViewColumns { get; set; }
        public virtual ICollection<ReportDataGrid> ReportDataGrids { get; set; }
        public virtual ICollection<ReportChart> ReportCharts { get; set; }
        public virtual ICollection<DataViewForDocumentTemplate> DataViewForDocumentTemplates { get; set; }
        public virtual ICollection<DocumentTemplateDataView> DocumentTemplateDataViews { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<DataViewLog> DataViewLogs { get; set; }
        public virtual ICollection<EmailTemplateCategory> EmailTemplateCategories { get; set; }
        public virtual ICollection<LetterCategory> LetterCategories { get; set; }
    }
}
