//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentFromTemplateData
    {
        public int Id { get; set; }
        public Nullable<int> DocumentFromTemplateRequestId { get; set; }
        public string DataName { get; set; }
        public string DataValue { get; set; }
        public string DataTypeName { get; set; }
    
        public virtual DocumentFromTemplateRequest DocumentFromTemplateRequest { get; set; }
    }
}
