//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentFromTemplateRequest
    {
        public DocumentFromTemplateRequest()
        {
            this.DocumentFromTemplateDatas = new HashSet<DocumentFromTemplateData>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DocumentTemplateId { get; set; }
        public string NewDocumentName { get; set; }
        public string NewDocumentPath { get; set; }
        public Nullable<int> RequestByUserId { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public Nullable<bool> RequestCompleted { get; set; }
        public string Comments { get; set; }
    
        public virtual ICollection<DocumentFromTemplateData> DocumentFromTemplateDatas { get; set; }
        public virtual DocumentTemplate DocumentTemplate { get; set; }
        public virtual User User { get; set; }
    }
}
