//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DORSControl
    {
        public int Id { get; set; }
        public bool DORSEnabled { get; set; }
        public int PasswordExpiryDays { get; set; }
        public Nullable<int> DORSStateId { get; set; }
        public Nullable<int> MaximumPostsPerSession { get; set; }
        public bool DORSSiteRefreshASAP { get; set; }
        public Nullable<System.DateTime> LastDORSSiteRefresh { get; set; }
    
        public virtual DORSState DORSState { get; set; }
    }
}
