//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DORSState
    {
        public DORSState()
        {
            this.DORSControls = new HashSet<DORSControl>();
            this.DORSConnections = new HashSet<DORSConnection>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> SystemStateId { get; set; }
    
        public virtual ICollection<DORSControl> DORSControls { get; set; }
        public virtual SystemState SystemState { get; set; }
        public virtual ICollection<DORSConnection> DORSConnections { get; set; }
    }
}
