//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DORSSite
    {
        public DORSSite()
        {
            this.DORSSiteVenues = new HashSet<DORSSiteVenue>();
            this.OrganisationDORSSites = new HashSet<OrganisationDORSSite>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DORSSiteIdentifier { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<DORSSiteVenue> DORSSiteVenues { get; set; }
        public virtual ICollection<OrganisationDORSSite> OrganisationDORSSites { get; set; }
    }
}
