//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DORSScheme
    {
        public DORSScheme()
        {
            this.ClientOnlineBookingStates = new HashSet<ClientOnlineBookingState>();
            this.DORSSchemeCourseTypes = new HashSet<DORSSchemeCourseType>();
            this.DORSTrainerSchemes = new HashSet<DORSTrainerScheme>();
            this.ClientDORSDatas = new HashSet<ClientDORSData>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> DORSSchemeIdentifier { get; set; }
        public int MinTheoryTrainers { get; set; }
        public int MinPracticalTrainers { get; set; }
        public int MaxTheoryTrainers { get; set; }
        public int MaxPracticalTrainers { get; set; }
        public int MaxPlaces { get; set; }
    
        public virtual ICollection<ClientOnlineBookingState> ClientOnlineBookingStates { get; set; }
        public virtual ICollection<DORSSchemeCourseType> DORSSchemeCourseTypes { get; set; }
        public virtual ICollection<DORSTrainerScheme> DORSTrainerSchemes { get; set; }
        public virtual ICollection<ClientDORSData> ClientDORSDatas { get; set; }
    }
}
