//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DORSCourseData
    {
        public int Id { get; set; }
        public Nullable<int> Availability { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<System.DateTime> CourseDate { get; set; }
        public Nullable<int> DORSCourseIdentifier { get; set; }
        public string Title { get; set; }
        public Nullable<int> DORSForceContractIdentifier { get; set; }
        public Nullable<int> DORSSiteIdentifier { get; set; }
        public Nullable<System.DateTime> DateSubmittedToDORS { get; set; }
    }
}
