//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DORSClientCourseAttendance
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public bool Attended { get; set; }
        public bool Completed { get; set; }
        public Nullable<int> DORSAttendanceRef { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> DORSAttendanceStateIdentifier { get; set; }
        public Nullable<System.DateTime> DORSExpiryDate { get; set; }
        public Nullable<int> DORSForceIdentifier { get; set; }
        public Nullable<int> DORSSchemeIdentifier { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Client Client { get; set; }
        public virtual User User { get; set; }
    }
}
