//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplate
    {
        public EmailTemplate()
        {
            this.EmailTemplateScheduledEmails = new HashSet<EmailTemplateScheduledEmail>();
        }
    
        public int Id { get; set; }
        public int OrganisationId { get; set; }
        public int EmailTemplateCategoryId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedByUserId { get; set; }
        public int VersionNumber { get; set; }
        public bool Enabled { get; set; }
    
        public virtual EmailTemplateCategory EmailTemplateCategory { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<EmailTemplateScheduledEmail> EmailTemplateScheduledEmails { get; set; }
    }
}
