//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public Email()
        {
            this.ClientEmails = new HashSet<ClientEmail>();
            this.VenueEmail = new HashSet<VenueEmail>();
            this.TrainerEmail = new HashSet<TrainerEmail>();
            this.OrganisationContacts = new HashSet<OrganisationContact>();
            this.InterpreterEmails = new HashSet<InterpreterEmail>();
            this.OrganisationContactCourseTypes = new HashSet<OrganisationContactCourseType>();
        }
    
        public int Id { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<ClientEmail> ClientEmails { get; set; }
        public virtual ICollection<VenueEmail> VenueEmail { get; set; }
        public virtual ICollection<TrainerEmail> TrainerEmail { get; set; }
        public virtual ICollection<OrganisationContact> OrganisationContacts { get; set; }
        public virtual ICollection<InterpreterEmail> InterpreterEmails { get; set; }
        public virtual ICollection<OrganisationContactCourseType> OrganisationContactCourseTypes { get; set; }
    }
}
