//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailServiceEmailCount
    {
        public int Id { get; set; }
        public int YearSent { get; set; }
        public int MonthSent { get; set; }
        public int WeekNumberSent { get; set; }
        public Nullable<int> NumberSent { get; set; }
        public Nullable<int> NumberSentMonday { get; set; }
        public Nullable<int> NumberSentTuesday { get; set; }
        public Nullable<int> NumberSentWednesday { get; set; }
        public Nullable<int> NumberSentThursday { get; set; }
        public Nullable<int> NumberSentFriday { get; set; }
        public Nullable<int> NumberSentSaturday { get; set; }
        public Nullable<int> NumberSentSunday { get; set; }
        public Nullable<int> EmailServiceId { get; set; }
    
        public virtual EmailService EmailService { get; set; }
    }
}
