//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailService
    {
        public EmailService()
        {
            this.EmailServiceNote = new HashSet<EmailServiceNote>();
            this.OrganisationPrefferedEmailService = new HashSet<OrganisationPrefferedEmailService>();
            this.EmailServiceSendingFailures = new HashSet<EmailServiceSendingFailure>();
            this.EmailServiceEmailCounts = new HashSet<EmailServiceEmailCount>();
            this.EmailServiceEmailsSents = new HashSet<EmailServiceEmailsSent>();
            this.EmailServiceCredentials = new HashSet<EmailServiceCredential>();
            this.ScheduledEmails = new HashSet<ScheduledEmail>();
            this.EmailServiceCredentialLogs = new HashSet<EmailServiceCredentialLog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Server { get; set; }
        public string AccessId { get; set; }
        public string AccessPassword { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<System.DateTime> DateLastUsed { get; set; }
        public Nullable<bool> Exclusive { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
    
        public virtual ICollection<EmailServiceNote> EmailServiceNote { get; set; }
        public virtual ICollection<OrganisationPrefferedEmailService> OrganisationPrefferedEmailService { get; set; }
        public virtual ICollection<EmailServiceSendingFailure> EmailServiceSendingFailures { get; set; }
        public virtual ICollection<EmailServiceEmailCount> EmailServiceEmailCounts { get; set; }
        public virtual ICollection<EmailServiceEmailsSent> EmailServiceEmailsSents { get; set; }
        public virtual ICollection<EmailServiceCredential> EmailServiceCredentials { get; set; }
        public virtual ICollection<ScheduledEmail> ScheduledEmails { get; set; }
        public virtual ICollection<EmailServiceCredentialLog> EmailServiceCredentialLogs { get; set; }
        public virtual User User { get; set; }
    }
}
