//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailServiceSendingFailure
    {
        public int Id { get; set; }
        public Nullable<int> EmailServiceId { get; set; }
        public Nullable<System.DateTime> DateFailed { get; set; }
        public string FailureInfo { get; set; }
    
        public virtual EmailService EmailService { get; set; }
    }
}
