//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileStoragePath
    {
        public FileStoragePath()
        {
            this.Documents = new HashSet<Document>();
            this.FileStoragePathOwners = new HashSet<FileStoragePathOwner>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<FileStoragePathOwner> FileStoragePathOwners { get; set; }
    }
}
