//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreqAskedQuestionAnswerRequest
    {
        public int Id { get; set; }
        public Nullable<int> FreqAskedQuestionAnswerId { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public Nullable<int> RequesteeUserId { get; set; }
        public Nullable<int> RequesterUserId { get; set; }
        public Nullable<bool> RequestCompleted { get; set; }
    
        public virtual FreqAskedQuestionAnswer FreqAskedQuestionAnswer { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
