//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreqAskedQuestionGroup
    {
        public FreqAskedQuestionGroup()
        {
            this.FreqAskedQuestionGroupItems = new HashSet<FreqAskedQuestionGroupItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> FreqAskedQuestionGroupCategoryId { get; set; }
    
        public virtual FreqAskedQuestionGroupCategory FreqAskedQuestionGroupCategory { get; set; }
        public virtual ICollection<FreqAskedQuestionGroupItem> FreqAskedQuestionGroupItems { get; set; }
    }
}
