//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterpreterLanguage
    {
        public int Id { get; set; }
        public int InterpreterId { get; set; }
        public int LanguageId { get; set; }
        public bool Main { get; set; }
    
        public virtual Interpreter Interpreter { get; set; }
        public virtual Language Language { get; set; }
    }
}
