//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LetterTemplateDocumentProcessRequest
    {
        public long ProcessRequestId { get; set; }
        public System.DateTime ProcessRequestDateTime { get; set; }
        public string ProcessFieldName { get; set; }
        public string ProcessFieldValue { get; set; }
    }
}
