//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LetterCategoryColumn
    {
        public int Id { get; set; }
        public int LetterCategoryId { get; set; }
        public int DataViewColumnId { get; set; }
        public string TagName { get; set; }
    
        public virtual DataViewColumn DataViewColumn { get; set; }
        public virtual LetterCategory LetterCategory { get; set; }
    }
}
