//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LetterTemplate
    {
        public LetterTemplate()
        {
            this.LetterTemplateDocuments = new HashSet<LetterTemplateDocument>();
        }
    
        public int Id { get; set; }
        public int OrganisationId { get; set; }
        public int LetterCategoryId { get; set; }
        public string Title { get; set; }
        public int TemplateDocumentId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedByUserId { get; set; }
        public int VersionNumber { get; set; }
        public bool Enabled { get; set; }
        public string IdKeyName { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual LetterCategory LetterCategory { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<LetterTemplateDocument> LetterTemplateDocuments { get; set; }
    }
}
