//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.ClientLocations = new HashSet<ClientLocation>();
            this.VenueAddress = new HashSet<VenueAddress>();
            this.TrainerLocation = new HashSet<TrainerLocation>();
            this.OrganisationContacts = new HashSet<OrganisationContact>();
            this.InterpreterLocations = new HashSet<InterpreterLocation>();
            this.OrganisationContactCourseTypes = new HashSet<OrganisationContactCourseType>();
        }
    
        public int Id { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual ICollection<ClientLocation> ClientLocations { get; set; }
        public virtual ICollection<VenueAddress> VenueAddress { get; set; }
        public virtual ICollection<TrainerLocation> TrainerLocation { get; set; }
        public virtual ICollection<OrganisationContact> OrganisationContacts { get; set; }
        public virtual ICollection<InterpreterLocation> InterpreterLocations { get; set; }
        public virtual ICollection<OrganisationContactCourseType> OrganisationContactCourseTypes { get; set; }
    }
}
