//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.MessageAcknowledgement = new HashSet<MessageAcknowledgement>();
            this.MessageRecipient = new HashSet<MessageRecipient>();
            this.MessageRecipientException = new HashSet<MessageRecipientException>();
            this.MessageRecipientOrganisation = new HashSet<MessageRecipientOrganisation>();
            this.MessageRecipientOrganisationException = new HashSet<MessageRecipientOrganisationException>();
            this.MessageSchedule = new HashSet<MessageSchedule>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public int MessageCategoryId { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<bool> AllUsers { get; set; }
    
        public virtual MessageCategory MessageCategory { get; set; }
        public virtual ICollection<MessageAcknowledgement> MessageAcknowledgement { get; set; }
        public virtual ICollection<MessageRecipient> MessageRecipient { get; set; }
        public virtual ICollection<MessageRecipientException> MessageRecipientException { get; set; }
        public virtual ICollection<MessageRecipientOrganisation> MessageRecipientOrganisation { get; set; }
        public virtual ICollection<MessageRecipientOrganisationException> MessageRecipientOrganisationException { get; set; }
        public virtual ICollection<MessageSchedule> MessageSchedule { get; set; }
        public virtual User User { get; set; }
    }
}
