//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetcallAgentNumberHistory
    {
        public int Id { get; set; }
        public int NetcallAgentId { get; set; }
        public string PreviousCallingNumber { get; set; }
        public string NewCallingNumber { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public int ChangedByUserId { get; set; }
    
        public virtual NetcallAgent NetcallAgent { get; set; }
        public virtual User User { get; set; }
    }
}
