//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public Note()
        {
            this.ClientNotes = new HashSet<ClientNote>();
            this.ClientPaymentNotes = new HashSet<ClientPaymentNote>();
            this.TrainerNotes = new HashSet<TrainerNote>();
            this.ReferringAuthorityNotes = new HashSet<ReferringAuthorityNote>();
            this.PaymentNotes = new HashSet<PaymentNote>();
            this.DORSConnectionNotes = new HashSet<DORSConnectionNote>();
            this.SchedulerControlNotes = new HashSet<SchedulerControlNote>();
            this.SystemFeatureUserNotes = new HashSet<SystemFeatureUserNote>();
            this.TrainerVenueNotes = new HashSet<TrainerVenueNote>();
            this.TrainerVehicleNotes = new HashSet<TrainerVehicleNote>();
            this.RefundNotes = new HashSet<RefundNote>();
            this.InterpreterNotes = new HashSet<InterpreterNote>();
            this.RefundRequestNotes = new HashSet<RefundRequestNote>();
            this.TaskNotes = new HashSet<TaskNote>();
        }
    
        public int Id { get; set; }
        public string Note1 { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public int CreatedByUserId { get; set; }
        public bool Removed { get; set; }
        public Nullable<int> NoteTypeId { get; set; }
    
        public virtual ICollection<ClientNote> ClientNotes { get; set; }
        public virtual ICollection<ClientPaymentNote> ClientPaymentNotes { get; set; }
        public virtual NoteType NoteType { get; set; }
        public virtual ICollection<TrainerNote> TrainerNotes { get; set; }
        public virtual ICollection<ReferringAuthorityNote> ReferringAuthorityNotes { get; set; }
        public virtual ICollection<PaymentNote> PaymentNotes { get; set; }
        public virtual ICollection<DORSConnectionNote> DORSConnectionNotes { get; set; }
        public virtual ICollection<SchedulerControlNote> SchedulerControlNotes { get; set; }
        public virtual ICollection<SystemFeatureUserNote> SystemFeatureUserNotes { get; set; }
        public virtual ICollection<TrainerVenueNote> TrainerVenueNotes { get; set; }
        public virtual ICollection<TrainerVehicleNote> TrainerVehicleNotes { get; set; }
        public virtual ICollection<RefundNote> RefundNotes { get; set; }
        public virtual ICollection<InterpreterNote> InterpreterNotes { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<RefundRequestNote> RefundRequestNotes { get; set; }
        public virtual ICollection<TaskNote> TaskNotes { get; set; }
    }
}
