//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineBookingLog
    {
        public int Id { get; set; }
        public string LicenceNumber { get; set; }
        public System.DateTime DateTimeEntered { get; set; }
        public string Browser { get; set; }
        public string OperatingSystem { get; set; }
        public string IPAddress { get; set; }
    }
}
