//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganisationContact
    {
        public int Id { get; set; }
        public int OrganisationId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> EmailId { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual Email Email { get; set; }
        public virtual Location Location { get; set; }
        public virtual Organisation Organisation { get; set; }
    }
}
