//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganisationLanguage
    {
        public OrganisationLanguage()
        {
            this.CourseLanguage = new HashSet<CourseLanguage>();
        }
    
        public int Id { get; set; }
        public int OrganisationId { get; set; }
        public int LanguageId { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<bool> Default { get; set; }
    
        public virtual ICollection<CourseLanguage> CourseLanguage { get; set; }
        public virtual Language Language { get; set; }
        public virtual Organisation Organisation { get; set; }
    }
}
