//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public Organisation()
        {
            this.OrganisationUsers = new HashSet<OrganisationUser>();
            this.ClientOrganisations = new HashSet<ClientOrganisation>();
            this.OrganisationAdminUsers = new HashSet<OrganisationAdminUser>();
            this.OrganisationReports = new HashSet<OrganisationReport>();
            this.OrganisationReportCategories = new HashSet<OrganisationReportCategory>();
            this.OrganisationPaymentType = new HashSet<OrganisationPaymentType>();
            this.OrganisationDisplay = new HashSet<OrganisationDisplay>();
            this.CourseType = new HashSet<CourseType>();
            this.Venue = new HashSet<Venue>();
            this.Area = new HashSet<Area>();
            this.OrganisationRegion = new HashSet<OrganisationRegion>();
            this.Course = new HashSet<Course>();
            this.MessageRecipientOrganisation = new HashSet<MessageRecipientOrganisation>();
            this.MessageRecipientOrganisationException = new HashSet<MessageRecipientOrganisationException>();
            this.TrainerOrganisation = new HashSet<TrainerOrganisation>();
            this.OrganisationPrefferedEmailService = new HashSet<OrganisationPrefferedEmailService>();
            this.VenueCostType = new HashSet<VenueCostType>();
            this.OrganisationLanguage = new HashSet<OrganisationLanguage>();
            this.ClientQuickSearches = new HashSet<ClientQuickSearch>();
            this.CourseQuickSearches = new HashSet<CourseQuickSearch>();
            this.OrganisationSystemConfigurations = new HashSet<OrganisationSystemConfiguration>();
            this.DORSConnections = new HashSet<DORSConnection>();
            this.OrganisationScheduledEmails = new HashSet<OrganisationScheduledEmail>();
            this.OrganisationPreferredSMSServices = new HashSet<OrganisationPreferredSMSService>();
            this.OrganisationContacts = new HashSet<OrganisationContact>();
            this.OrganisationManagements = new HashSet<OrganisationManagement>();
            this.OrganisationManagements1 = new HashSet<OrganisationManagement>();
            this.AdministrationMenuItemOrganisations = new HashSet<AdministrationMenuItemOrganisation>();
            this.CourseReferenceDateFormats = new HashSet<CourseReferenceDateFormat>();
            this.CourseReferenceNumbers = new HashSet<CourseReferenceNumber>();
            this.CourseReferencePrefixSuffixSeparators = new HashSet<CourseReferencePrefixSuffixSeparator>();
            this.SystemStateSummaries = new HashSet<SystemStateSummary>();
            this.SystemStateSummaryHistories = new HashSet<SystemStateSummaryHistory>();
            this.PaymentMethods = new HashSet<PaymentMethod>();
            this.OrganisationDORSForceContracts = new HashSet<OrganisationDORSForceContract>();
            this.OrganisationSMSTemplateMessages = new HashSet<OrganisationSMSTemplateMessage>();
            this.OrganisationPaymentProviders = new HashSet<OrganisationPaymentProvider>();
            this.OrganisationPaymentProviderCredentials = new HashSet<OrganisationPaymentProviderCredential>();
            this.DocumentOwners = new HashSet<DocumentOwner>();
            this.FileStoragePathOwners = new HashSet<FileStoragePathOwner>();
            this.OrganisationDashboardMeters = new HashSet<OrganisationDashboardMeter>();
            this.ReferringAuthorities = new HashSet<ReferringAuthority>();
            this.ReferringAuthorityContracts = new HashSet<ReferringAuthorityContract>();
            this.SpecialRequirements = new HashSet<SpecialRequirement>();
            this.TrainerDocuments = new HashSet<TrainerDocument>();
            this.AllCourseDocuments = new HashSet<AllCourseDocument>();
            this.AllTrainerDocuments = new HashSet<AllTrainerDocument>();
            this.SystemSupportUsers = new HashSet<SystemSupportUser>();
            this.DashboardMeter_DocumentSummary = new HashSet<DashboardMeter_DocumentSummary>();
            this.EmailsBlockedOutgoings = new HashSet<EmailsBlockedOutgoing>();
            this.OrganisationSystemTaskMessagings = new HashSet<OrganisationSystemTaskMessaging>();
            this.DashboardMeterExposures = new HashSet<DashboardMeterExposure>();
            this.EmailServiceEmailsSents = new HashSet<EmailServiceEmailsSent>();
            this.OrganisationEmailCounts = new HashSet<OrganisationEmailCount>();
            this.OrganisationEmailTemplateMessages = new HashSet<OrganisationEmailTemplateMessage>();
            this.SystemFeatureUserNotes = new HashSet<SystemFeatureUserNote>();
            this.SystemInformations = new HashSet<SystemInformation>();
            this.OrganisationSelfConfigurations = new HashSet<OrganisationSelfConfiguration>();
            this.OrganisationCourseStencils = new HashSet<OrganisationCourseStencil>();
            this.ArchivedSMS = new HashSet<ArchivedSM>();
            this.ScheduledSMS = new HashSet<ScheduledSM>();
            this.OrganisationScheduledSMS = new HashSet<OrganisationScheduledSM>();
            this.CourseCloneRequests = new HashSet<CourseCloneRequest>();
            this.ReferringAuthorityOrganisations = new HashSet<ReferringAuthorityOrganisation>();
            this.OrganisationPayments = new HashSet<OrganisationPayment>();
            this.OrganisationArchiveControls = new HashSet<OrganisationArchiveControl>();
            this.ArchivedEmails = new HashSet<ArchivedEmail>();
            this.CourseTypeCategoryFees = new HashSet<CourseTypeCategoryFee>();
            this.CourseTypeCategoryRebookingFees = new HashSet<CourseTypeCategoryRebookingFee>();
            this.CourseTypeFees = new HashSet<CourseTypeFee>();
            this.CourseTypeRebookingFees = new HashSet<CourseTypeRebookingFee>();
            this.Refunds = new HashSet<Refund>();
            this.RefundMethods = new HashSet<RefundMethod>();
            this.RefundTypes = new HashSet<RefundType>();
            this.InterpreterOrganisations = new HashSet<InterpreterOrganisation>();
            this.ClientOnlineBookingRestrictions = new HashSet<ClientOnlineBookingRestriction>();
            this.NetcallAgents = new HashSet<NetcallAgent>();
            this.RefundRequests = new HashSet<RefundRequest>();
            this.TaskCategoryForOrganisations = new HashSet<TaskCategoryForOrganisation>();
            this.TaskForOrganisations = new HashSet<TaskForOrganisation>();
            this.TaskRemovedFromOrganisations = new HashSet<TaskRemovedFromOrganisation>();
            this.TaskActionPriorityForOrganisations = new HashSet<TaskActionPriorityForOrganisation>();
            this.OrganisationDORSSites = new HashSet<OrganisationDORSSite>();
            this.VehicleTypes = new HashSet<VehicleType>();
            this.VehicleCategories = new HashSet<VehicleCategory>();
            this.ReportRequests = new HashSet<ReportRequest>();
            this.DashboardMeterData_Client = new HashSet<DashboardMeterData_Client>();
            this.DashboardMeterData_Course = new HashSet<DashboardMeterData_Course>();
            this.DashboardMeterData_DocumentStat = new HashSet<DashboardMeterData_DocumentStat>();
            this.DashboardMeterData_DORSOfferWithdrawn = new HashSet<DashboardMeterData_DORSOfferWithdrawn>();
            this.DashboardMeterData_Email = new HashSet<DashboardMeterData_Email>();
            this.DashboardMeterData_OnlineClientsSpecialRequirement = new HashSet<DashboardMeterData_OnlineClientsSpecialRequirement>();
            this.DashboardMeterData_Payment = new HashSet<DashboardMeterData_Payment>();
            this.DashboardMeterData_UnpaidBookedCourse = new HashSet<DashboardMeterData_UnpaidBookedCourse>();
            this.OldLetterTemplates = new HashSet<OldLetterTemplate>();
            this.EmailTemplates = new HashSet<EmailTemplate>();
            this.LetterTemplates = new HashSet<LetterTemplate>();
            this.OrganisationInterpreterSettings = new HashSet<OrganisationInterpreterSetting>();
            this.OrganisationTrainerSettings = new HashSet<OrganisationTrainerSetting>();
            this.ReportQueues = new HashSet<ReportQueue>();
            this.DocumentPrintQueues = new HashSet<DocumentPrintQueue>();
            this.OrganisationContactCourseTypes = new HashSet<OrganisationContactCourseType>();
            this.ClientEmailTemplates = new HashSet<ClientEmailTemplate>();
            this.SystemTrainerInformationByOrganisations = new HashSet<SystemTrainerInformationByOrganisation>();
            this.ReconciliationConfigurations = new HashSet<ReconciliationConfiguration>();
            this.DashboardMeterData_UnableToUpdateInDORS = new HashSet<DashboardMeterData_UnableToUpdateInDORS>();
            this.DashboardMeterData_AttendanceNotUploadedToDORS = new HashSet<DashboardMeterData_AttendanceNotUploadedToDORS>();
            this.OrganisationCourses = new HashSet<OrganisationCourse>();
            this.PaymentErrorInformations = new HashSet<PaymentErrorInformation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public string PreviousSystemName { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
    
        public virtual ICollection<OrganisationUser> OrganisationUsers { get; set; }
        public virtual ICollection<ClientOrganisation> ClientOrganisations { get; set; }
        public virtual ICollection<OrganisationAdminUser> OrganisationAdminUsers { get; set; }
        public virtual ICollection<OrganisationReport> OrganisationReports { get; set; }
        public virtual ICollection<OrganisationReportCategory> OrganisationReportCategories { get; set; }
        public virtual ICollection<OrganisationPaymentType> OrganisationPaymentType { get; set; }
        public virtual ICollection<OrganisationDisplay> OrganisationDisplay { get; set; }
        public virtual ICollection<CourseType> CourseType { get; set; }
        public virtual ICollection<Venue> Venue { get; set; }
        public virtual ICollection<Area> Area { get; set; }
        public virtual ICollection<OrganisationRegion> OrganisationRegion { get; set; }
        public virtual ICollection<Course> Course { get; set; }
        public virtual ICollection<MessageRecipientOrganisation> MessageRecipientOrganisation { get; set; }
        public virtual ICollection<MessageRecipientOrganisationException> MessageRecipientOrganisationException { get; set; }
        public virtual ICollection<TrainerOrganisation> TrainerOrganisation { get; set; }
        public virtual ICollection<OrganisationPrefferedEmailService> OrganisationPrefferedEmailService { get; set; }
        public virtual ICollection<VenueCostType> VenueCostType { get; set; }
        public virtual ICollection<OrganisationLanguage> OrganisationLanguage { get; set; }
        public virtual ICollection<ClientQuickSearch> ClientQuickSearches { get; set; }
        public virtual ICollection<CourseQuickSearch> CourseQuickSearches { get; set; }
        public virtual ICollection<OrganisationSystemConfiguration> OrganisationSystemConfigurations { get; set; }
        public virtual ICollection<DORSConnection> DORSConnections { get; set; }
        public virtual ICollection<OrganisationScheduledEmail> OrganisationScheduledEmails { get; set; }
        public virtual ICollection<OrganisationPreferredSMSService> OrganisationPreferredSMSServices { get; set; }
        public virtual ICollection<OrganisationContact> OrganisationContacts { get; set; }
        public virtual ICollection<OrganisationManagement> OrganisationManagements { get; set; }
        public virtual ICollection<OrganisationManagement> OrganisationManagements1 { get; set; }
        public virtual ICollection<AdministrationMenuItemOrganisation> AdministrationMenuItemOrganisations { get; set; }
        public virtual ICollection<CourseReferenceDateFormat> CourseReferenceDateFormats { get; set; }
        public virtual ICollection<CourseReferenceNumber> CourseReferenceNumbers { get; set; }
        public virtual ICollection<CourseReferencePrefixSuffixSeparator> CourseReferencePrefixSuffixSeparators { get; set; }
        public virtual ICollection<SystemStateSummary> SystemStateSummaries { get; set; }
        public virtual ICollection<SystemStateSummaryHistory> SystemStateSummaryHistories { get; set; }
        public virtual ICollection<PaymentMethod> PaymentMethods { get; set; }
        public virtual ICollection<OrganisationDORSForceContract> OrganisationDORSForceContracts { get; set; }
        public virtual ICollection<OrganisationSMSTemplateMessage> OrganisationSMSTemplateMessages { get; set; }
        public virtual ICollection<OrganisationPaymentProvider> OrganisationPaymentProviders { get; set; }
        public virtual ICollection<OrganisationPaymentProviderCredential> OrganisationPaymentProviderCredentials { get; set; }
        public virtual ICollection<DocumentOwner> DocumentOwners { get; set; }
        public virtual ICollection<FileStoragePathOwner> FileStoragePathOwners { get; set; }
        public virtual ICollection<OrganisationDashboardMeter> OrganisationDashboardMeters { get; set; }
        public virtual ICollection<ReferringAuthority> ReferringAuthorities { get; set; }
        public virtual ICollection<ReferringAuthorityContract> ReferringAuthorityContracts { get; set; }
        public virtual ICollection<SpecialRequirement> SpecialRequirements { get; set; }
        public virtual ICollection<TrainerDocument> TrainerDocuments { get; set; }
        public virtual ICollection<AllCourseDocument> AllCourseDocuments { get; set; }
        public virtual ICollection<AllTrainerDocument> AllTrainerDocuments { get; set; }
        public virtual ICollection<SystemSupportUser> SystemSupportUsers { get; set; }
        public virtual ICollection<DashboardMeter_DocumentSummary> DashboardMeter_DocumentSummary { get; set; }
        public virtual ICollection<EmailsBlockedOutgoing> EmailsBlockedOutgoings { get; set; }
        public virtual ICollection<OrganisationSystemTaskMessaging> OrganisationSystemTaskMessagings { get; set; }
        public virtual ICollection<DashboardMeterExposure> DashboardMeterExposures { get; set; }
        public virtual ICollection<EmailServiceEmailsSent> EmailServiceEmailsSents { get; set; }
        public virtual ICollection<OrganisationEmailCount> OrganisationEmailCounts { get; set; }
        public virtual ICollection<OrganisationEmailTemplateMessage> OrganisationEmailTemplateMessages { get; set; }
        public virtual ICollection<SystemFeatureUserNote> SystemFeatureUserNotes { get; set; }
        public virtual ICollection<SystemInformation> SystemInformations { get; set; }
        public virtual ICollection<OrganisationSelfConfiguration> OrganisationSelfConfigurations { get; set; }
        public virtual ICollection<OrganisationCourseStencil> OrganisationCourseStencils { get; set; }
        public virtual ICollection<ArchivedSM> ArchivedSMS { get; set; }
        public virtual ICollection<ScheduledSM> ScheduledSMS { get; set; }
        public virtual ICollection<OrganisationScheduledSM> OrganisationScheduledSMS { get; set; }
        public virtual ICollection<CourseCloneRequest> CourseCloneRequests { get; set; }
        public virtual ICollection<ReferringAuthorityOrganisation> ReferringAuthorityOrganisations { get; set; }
        public virtual ICollection<OrganisationPayment> OrganisationPayments { get; set; }
        public virtual ICollection<OrganisationArchiveControl> OrganisationArchiveControls { get; set; }
        public virtual ICollection<ArchivedEmail> ArchivedEmails { get; set; }
        public virtual ICollection<CourseTypeCategoryFee> CourseTypeCategoryFees { get; set; }
        public virtual ICollection<CourseTypeCategoryRebookingFee> CourseTypeCategoryRebookingFees { get; set; }
        public virtual ICollection<CourseTypeFee> CourseTypeFees { get; set; }
        public virtual ICollection<CourseTypeRebookingFee> CourseTypeRebookingFees { get; set; }
        public virtual ICollection<Refund> Refunds { get; set; }
        public virtual ICollection<RefundMethod> RefundMethods { get; set; }
        public virtual ICollection<RefundType> RefundTypes { get; set; }
        public virtual ICollection<InterpreterOrganisation> InterpreterOrganisations { get; set; }
        public virtual ICollection<ClientOnlineBookingRestriction> ClientOnlineBookingRestrictions { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<NetcallAgent> NetcallAgents { get; set; }
        public virtual ICollection<RefundRequest> RefundRequests { get; set; }
        public virtual ICollection<TaskCategoryForOrganisation> TaskCategoryForOrganisations { get; set; }
        public virtual ICollection<TaskForOrganisation> TaskForOrganisations { get; set; }
        public virtual ICollection<TaskRemovedFromOrganisation> TaskRemovedFromOrganisations { get; set; }
        public virtual ICollection<TaskActionPriorityForOrganisation> TaskActionPriorityForOrganisations { get; set; }
        public virtual ICollection<OrganisationDORSSite> OrganisationDORSSites { get; set; }
        public virtual ICollection<VehicleType> VehicleTypes { get; set; }
        public virtual ICollection<VehicleCategory> VehicleCategories { get; set; }
        public virtual ICollection<ReportRequest> ReportRequests { get; set; }
        public virtual ICollection<DashboardMeterData_Client> DashboardMeterData_Client { get; set; }
        public virtual ICollection<DashboardMeterData_Course> DashboardMeterData_Course { get; set; }
        public virtual ICollection<DashboardMeterData_DocumentStat> DashboardMeterData_DocumentStat { get; set; }
        public virtual ICollection<DashboardMeterData_DORSOfferWithdrawn> DashboardMeterData_DORSOfferWithdrawn { get; set; }
        public virtual ICollection<DashboardMeterData_Email> DashboardMeterData_Email { get; set; }
        public virtual ICollection<DashboardMeterData_OnlineClientsSpecialRequirement> DashboardMeterData_OnlineClientsSpecialRequirement { get; set; }
        public virtual ICollection<DashboardMeterData_Payment> DashboardMeterData_Payment { get; set; }
        public virtual ICollection<DashboardMeterData_UnpaidBookedCourse> DashboardMeterData_UnpaidBookedCourse { get; set; }
        public virtual ICollection<OldLetterTemplate> OldLetterTemplates { get; set; }
        public virtual ICollection<EmailTemplate> EmailTemplates { get; set; }
        public virtual ICollection<LetterTemplate> LetterTemplates { get; set; }
        public virtual ICollection<OrganisationInterpreterSetting> OrganisationInterpreterSettings { get; set; }
        public virtual ICollection<OrganisationTrainerSetting> OrganisationTrainerSettings { get; set; }
        public virtual ICollection<ReportQueue> ReportQueues { get; set; }
        public virtual ICollection<DocumentPrintQueue> DocumentPrintQueues { get; set; }
        public virtual ICollection<OrganisationContactCourseType> OrganisationContactCourseTypes { get; set; }
        public virtual ICollection<ClientEmailTemplate> ClientEmailTemplates { get; set; }
        public virtual ICollection<SystemTrainerInformationByOrganisation> SystemTrainerInformationByOrganisations { get; set; }
        public virtual ICollection<ReconciliationConfiguration> ReconciliationConfigurations { get; set; }
        public virtual ICollection<DashboardMeterData_UnableToUpdateInDORS> DashboardMeterData_UnableToUpdateInDORS { get; set; }
        public virtual ICollection<DashboardMeterData_AttendanceNotUploadedToDORS> DashboardMeterData_AttendanceNotUploadedToDORS { get; set; }
        public virtual ICollection<OrganisationCourse> OrganisationCourses { get; set; }
        public virtual ICollection<PaymentErrorInformation> PaymentErrorInformations { get; set; }
    }
}
