//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCardValidationTypeLength
    {
        public int Id { get; set; }
        public int PaymentCardValidationTypeId { get; set; }
        public int ValidLength { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime DateTimeCreated { get; set; }
        public bool Disabled { get; set; }
        public Nullable<System.DateTime> DateTimeDisabled { get; set; }
        public Nullable<int> DisabledByUserId { get; set; }
    
        public virtual PaymentCardValidationType PaymentCardValidationType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
