//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.ClientPayment = new HashSet<ClientPayment>();
            this.ClientPaymentLink = new HashSet<ClientPaymentLink>();
            this.ClientPaymentNote = new HashSet<ClientPaymentNote>();
            this.PaymentPreviousId = new HashSet<PaymentPreviousId>();
            this.ClientPaymentPreviousClientId = new HashSet<ClientPaymentPreviousClientId>();
            this.CourseClientPayments = new HashSet<CourseClientPayment>();
            this.PaymentCards = new HashSet<PaymentCard>();
            this.PaymentCardLogs = new HashSet<PaymentCardLog>();
            this.PaymentLinks = new HashSet<PaymentLink>();
            this.PaymentLinks1 = new HashSet<PaymentLink>();
            this.PaymentNotes = new HashSet<PaymentNote>();
            this.NetcallPayments = new HashSet<NetcallPayment>();
            this.OrganisationPayments = new HashSet<OrganisationPayment>();
            this.CourseClientPaymentTransfers = new HashSet<CourseClientPaymentTransfer>();
            this.RefundPayments = new HashSet<RefundPayment>();
            this.RefundPayments1 = new HashSet<RefundPayment>();
            this.NetcallOverridePayments = new HashSet<NetcallOverridePayment>();
            this.RefundRequests = new HashSet<RefundRequest>();
            this.ReconciliationDatas = new HashSet<ReconciliationData>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public string ReceiptNumber { get; set; }
        public string AuthCode { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<bool> CardPayment { get; set; }
        public Nullable<bool> Refund { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public string PaymentName { get; set; }
        public string Reference { get; set; }
        public Nullable<bool> NetcallPayment { get; set; }
    
        public virtual ICollection<ClientPayment> ClientPayment { get; set; }
        public virtual ICollection<ClientPaymentLink> ClientPaymentLink { get; set; }
        public virtual ICollection<ClientPaymentNote> ClientPaymentNote { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual ICollection<PaymentPreviousId> PaymentPreviousId { get; set; }
        public virtual ICollection<ClientPaymentPreviousClientId> ClientPaymentPreviousClientId { get; set; }
        public virtual ICollection<CourseClientPayment> CourseClientPayments { get; set; }
        public virtual ICollection<PaymentCard> PaymentCards { get; set; }
        public virtual ICollection<PaymentCardLog> PaymentCardLogs { get; set; }
        public virtual ICollection<PaymentLink> PaymentLinks { get; set; }
        public virtual ICollection<PaymentLink> PaymentLinks1 { get; set; }
        public virtual ICollection<PaymentNote> PaymentNotes { get; set; }
        public virtual ICollection<NetcallPayment> NetcallPayments { get; set; }
        public virtual ICollection<OrganisationPayment> OrganisationPayments { get; set; }
        public virtual ICollection<CourseClientPaymentTransfer> CourseClientPaymentTransfers { get; set; }
        public virtual ICollection<RefundPayment> RefundPayments { get; set; }
        public virtual ICollection<RefundPayment> RefundPayments1 { get; set; }
        public virtual ICollection<NetcallOverridePayment> NetcallOverridePayments { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<RefundRequest> RefundRequests { get; set; }
        public virtual ICollection<ReconciliationData> ReconciliationDatas { get; set; }
    }
}
