//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCard
    {
        public PaymentCard()
        {
            this.PaymentCardLogs = new HashSet<PaymentCardLog>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> PaymentCardSupplierId { get; set; }
        public Nullable<int> PaymentProviderId { get; set; }
        public string PaymentProviderTransactionReference { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> PaymentCardTypeId { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual PaymentCardSupplier PaymentCardSupplier { get; set; }
        public virtual ICollection<PaymentCardLog> PaymentCardLogs { get; set; }
        public virtual PaymentCardType PaymentCardType { get; set; }
        public virtual PaymentProvider PaymentProvider { get; set; }
        public virtual User User { get; set; }
    }
}
