//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCardSupplier
    {
        public PaymentCardSupplier()
        {
            this.PaymentCards = new HashSet<PaymentCard>();
            this.PaymentCardLogs = new HashSet<PaymentCardLog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<int> PaymentCardProviderId { get; set; }
    
        public virtual ICollection<PaymentCard> PaymentCards { get; set; }
        public virtual ICollection<PaymentCardLog> PaymentCardLogs { get; set; }
        public virtual PaymentCardProvider PaymentCardProvider { get; set; }
    }
}
