//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public PaymentMethod()
        {
            this.Payment = new HashSet<Payment>();
            this.PaymentCardTypePaymentMethods = new HashSet<PaymentCardTypePaymentMethod>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public Nullable<bool> Disabled { get; set; }
    
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual ICollection<PaymentCardTypePaymentMethod> PaymentCardTypePaymentMethods { get; set; }
    }
}
