//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingEmailAttachment
    {
        public PendingEmailAttachment()
        {
            this.PendingEmailAttachment1 = new HashSet<PendingEmailAttachment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SameEmailAs_PendingEmailAttachmentId { get; set; }
        public int DocumentId { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual ICollection<PendingEmailAttachment> PendingEmailAttachment1 { get; set; }
        public virtual PendingEmailAttachment PendingEmailAttachment2 { get; set; }
    }
}
