//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodicalSPJob
    {
        public PeriodicalSPJob()
        {
            this.PeriodicalSPJobCalls = new HashSet<PeriodicalSPJobCall>();
        }
    
        public int Id { get; set; }
        public string StoredProcedureName { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> DateLastRun { get; set; }
        public bool Disabled { get; set; }
        public Nullable<int> RunEveryAfterMinutes { get; set; }
        public Nullable<int> RunAfterDays { get; set; }
        public Nullable<int> RunAfterMonths { get; set; }
        public System.DateTime DueDateTime { get; set; }
        public Nullable<int> RunOnlyOnDayNumber { get; set; }
        public bool RunOnlyOnWeekends { get; set; }
        public bool RunOnlyOnWeekdays { get; set; }
        public System.TimeSpan RunOnOrAfterTime { get; set; }
        public System.TimeSpan RunOnOrBeforeTime { get; set; }
        public Nullable<System.DateTime> LastDateTimeStarted { get; set; }
    
        public virtual ICollection<PeriodicalSPJobCall> PeriodicalSPJobCalls { get; set; }
    }
}
