//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reconciliation
    {
        public Reconciliation()
        {
            this.ReconciliationDatas = new HashSet<ReconciliationData>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedByUserId { get; set; }
        public string Reference { get; set; }
        public int ReconciliationConfigurationId { get; set; }
        public string ImportedFileName { get; set; }
        public System.DateTime PaymentStartDate { get; set; }
        public System.DateTime PaymentEndDate { get; set; }
        public bool RefreshPaymentData { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public string Name { get; set; }
    
        public virtual ReconciliationConfiguration ReconciliationConfiguration { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ReconciliationData> ReconciliationDatas { get; set; }
        public virtual Document Document { get; set; }
    }
}
