//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReconciliationConfiguration
    {
        public ReconciliationConfiguration()
        {
            this.Reconciliations = new HashSet<Reconciliation>();
        }
    
        public int Id { get; set; }
        public int OrganisationId { get; set; }
        public string Name { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<int> TransactionDateColumnNumber { get; set; }
        public Nullable<int> TransactionAmountColumnNumber { get; set; }
        public Nullable<int> Reference1ColumnNumber { get; set; }
        public Nullable<int> Reference2ColumnNumber { get; set; }
        public Nullable<int> Reference3ColumnNumber { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual ICollection<Reconciliation> Reconciliations { get; set; }
        public virtual User User { get; set; }
    }
}
