//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferringAuthorityUser
    {
        public ReferringAuthorityUser()
        {
            this.ReferringAuthorityUserDepartments = new HashSet<ReferringAuthorityUserDepartment>();
        }
    
        public int Id { get; set; }
        public int ReferringAuthorityId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int AddedByUserId { get; set; }
    
        public virtual ReferringAuthority ReferringAuthority { get; set; }
        public virtual ICollection<ReferringAuthorityUserDepartment> ReferringAuthorityUserDepartments { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
