//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferringAuthorityDepartment
    {
        public int Id { get; set; }
        public Nullable<int> ReferringAuthorityId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
    
        public virtual ReferringAuthority ReferringAuthority { get; set; }
        public virtual User User { get; set; }
    }
}
