//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferringAuthorityContract
    {
        public int Id { get; set; }
        public int ReferringAuthorityId { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int ContractedOrganisationId { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ReferringAuthority ReferringAuthority { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual User User { get; set; }
    }
}
