//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refund
    {
        public Refund()
        {
            this.CancelledRefunds = new HashSet<CancelledRefund>();
            this.RefundNotes = new HashSet<RefundNote>();
            this.RefundPayments = new HashSet<RefundPayment>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int RefundMethodId { get; set; }
        public int RefundTypeId { get; set; }
        public int CreatedByUserId { get; set; }
        public string Reference { get; set; }
        public string PaymentName { get; set; }
        public int OrganisationId { get; set; }
    
        public virtual ICollection<CancelledRefund> CancelledRefunds { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual RefundMethod RefundMethod { get; set; }
        public virtual ICollection<RefundNote> RefundNotes { get; set; }
        public virtual ICollection<RefundPayment> RefundPayments { get; set; }
        public virtual RefundType RefundType { get; set; }
        public virtual User User { get; set; }
    }
}
