//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.DashboardReports = new HashSet<DashboardReport>();
            this.ReportCharts = new HashSet<ReportChart>();
            this.ReportDataGrids = new HashSet<ReportDataGrid>();
            this.ReportExportOptions = new HashSet<ReportExportOption>();
            this.ReportsReportCategories = new HashSet<ReportsReportCategory>();
            this.OrganisationReports = new HashSet<OrganisationReport>();
            this.ReportOwners = new HashSet<ReportOwner>();
            this.UserReports = new HashSet<UserReport>();
            this.ScheduledReport = new HashSet<ScheduledReport>();
            this.ReportRequests = new HashSet<ReportRequest>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public bool AtlasSystemReport { get; set; }
        public bool Landscape { get; set; }
        public int ChangeNo { get; set; }
    
        public virtual ICollection<DashboardReport> DashboardReports { get; set; }
        public virtual ICollection<ReportChart> ReportCharts { get; set; }
        public virtual ICollection<ReportDataGrid> ReportDataGrids { get; set; }
        public virtual ICollection<ReportExportOption> ReportExportOptions { get; set; }
        public virtual ICollection<ReportsReportCategory> ReportsReportCategories { get; set; }
        public virtual ICollection<OrganisationReport> OrganisationReports { get; set; }
        public virtual ICollection<ReportOwner> ReportOwners { get; set; }
        public virtual ICollection<UserReport> UserReports { get; set; }
        public virtual ICollection<ScheduledReport> ScheduledReport { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<ReportRequest> ReportRequests { get; set; }
    }
}
