//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportQueue
    {
        public ReportQueue()
        {
            this.ReportQueueRequests = new HashSet<ReportQueueRequest>();
        }
    
        public int Id { get; set; }
        public int OrganisationId { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateTimeLastRun { get; set; }
        public Nullable<int> LastRunByUserId { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<ReportQueueRequest> ReportQueueRequests { get; set; }
    }
}
