//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportCategory
    {
        public ReportCategory()
        {
            this.ReportsReportCategories = new HashSet<ReportsReportCategory>();
            this.OrganisationReportCategories = new HashSet<OrganisationReportCategory>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Disabled { get; set; }
    
        public virtual ICollection<ReportsReportCategory> ReportsReportCategories { get; set; }
        public virtual ICollection<OrganisationReportCategory> OrganisationReportCategories { get; set; }
    }
}
