//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDataTypeSelectIdentifier
    {
        public int Id { get; set; }
        public int ReportDataTypeId { get; set; }
        public string SelectIdentifier { get; set; }
    
        public virtual ReportDataType ReportDataType { get; set; }
    }
}
