//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportChart
    {
        public ReportChart()
        {
            this.ReportChartColumns = new HashSet<ReportChartColumn>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ReportId { get; set; }
        public string ChartType { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> DataViewId { get; set; }
    
        public virtual Report Report { get; set; }
        public virtual DataView DataView { get; set; }
        public virtual ICollection<ReportChartColumn> ReportChartColumns { get; set; }
    }
}
