//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledReport
    {
        public ScheduledReport()
        {
            this.ScheduledReportEmailTo = new HashSet<ScheduledReportEmailTo>();
            this.ScheduledReportHistory = new HashSet<ScheduledReportHistory>();
            this.ScheduledReportParameter = new HashSet<ScheduledReportParameter>();
        }
    
        public int Id { get; set; }
        public int ReportId { get; set; }
        public Nullable<System.DateTime> LastSent { get; set; }
        public Nullable<System.DateTime> NextDue { get; set; }
        public string FrequencyCode { get; set; }
        public Nullable<bool> Disabled { get; set; }
    
        public virtual Report Report { get; set; }
        public virtual ICollection<ScheduledReportEmailTo> ScheduledReportEmailTo { get; set; }
        public virtual ICollection<ScheduledReportHistory> ScheduledReportHistory { get; set; }
        public virtual ICollection<ScheduledReportParameter> ScheduledReportParameter { get; set; }
    }
}
