//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledEmailState
    {
        public ScheduledEmailState()
        {
            this.ScheduledEmails = new HashSet<ScheduledEmail>();
            this.ArchivedEmails = new HashSet<ArchivedEmail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ScheduledEmail> ScheduledEmails { get; set; }
        public virtual ICollection<ArchivedEmail> ArchivedEmails { get; set; }
    }
}
