//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledEmailNote
    {
        public int Id { get; set; }
        public int ScheduledEmailId { get; set; }
        public string Note { get; set; }
    
        public virtual ScheduledEmail ScheduledEmail { get; set; }
    }
}
