//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchHistoryUser
    {
        public SearchHistoryUser()
        {
            this.SearchHistoryItem = new HashSet<SearchHistoryItem>();
        }
    
        public int Id { get; set; }
        public int SearchHistoryInterfaceId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual SearchHistoryInterface SearchHistoryInterface { get; set; }
        public virtual ICollection<SearchHistoryItem> SearchHistoryItem { get; set; }
        public virtual User User { get; set; }
    }
}
