//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSServiceMessageCount
    {
        public int Id { get; set; }
        public Nullable<int> YearSent { get; set; }
        public Nullable<int> MonthSent { get; set; }
        public Nullable<int> WeekNumberSent { get; set; }
        public Nullable<int> NumberSent { get; set; }
    }
}
