//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemTask
    {
        public SystemTask()
        {
            this.OrganisationSystemTaskMessagings = new HashSet<OrganisationSystemTaskMessaging>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string DevelopersNotes { get; set; }
        public string EmailOptionCaption { get; set; }
        public string InternalMessageOptionCaption { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ICollection<OrganisationSystemTaskMessaging> OrganisationSystemTaskMessagings { get; set; }
    }
}
