//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemFeatureGroupItem
    {
        public int Id { get; set; }
        public Nullable<int> SystemFeatureGroupId { get; set; }
        public Nullable<int> SystemFeatureItemId { get; set; }
    
        public virtual SystemFeatureGroup SystemFeatureGroup { get; set; }
        public virtual SystemFeatureItem SystemFeatureItem { get; set; }
    }
}
