//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemState
    {
        public SystemState()
        {
            this.DORSStates = new HashSet<DORSState>();
            this.SystemStateSummaries = new HashSet<SystemStateSummary>();
            this.SystemStateSummaryHistories = new HashSet<SystemStateSummaryHistory>();
        }
    
        public int Id { get; set; }
        public string Colour { get; set; }
        public string ColourHexCode { get; set; }
        public string ImageName { get; set; }
    
        public virtual ICollection<DORSState> DORSStates { get; set; }
        public virtual ICollection<SystemStateSummary> SystemStateSummaries { get; set; }
        public virtual ICollection<SystemStateSummaryHistory> SystemStateSummaryHistories { get; set; }
    }
}
