//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemStateSummaryHistory
    {
        public int Id { get; set; }
        public Nullable<int> SystemStateSummaryId { get; set; }
        public int OrganisationId { get; set; }
        public string Code { get; set; }
        public string Message { get; set; }
        public Nullable<int> SystemStateId { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public Nullable<int> AddedByUserId { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual SystemState SystemState { get; set; }
        public virtual SystemStateSummary SystemStateSummary { get; set; }
        public virtual User User { get; set; }
    }
}
