//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAction
    {
        public TaskAction()
        {
            this.TaskActionPriorityForOrganisations = new HashSet<TaskActionPriorityForOrganisation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int PriorityNumber { get; set; }
        public bool AssignToOrganisation { get; set; }
        public bool AssignToOrganisationAdminstrators { get; set; }
        public bool AssignToOrganisationSupportGroup { get; set; }
        public bool AssignToAtlasSystemAdministrators { get; set; }
        public bool AssignToAtlasSystemSupportGroup { get; set; }
    
        public virtual ICollection<TaskActionPriorityForOrganisation> TaskActionPriorityForOrganisations { get; set; }
    }
}
