//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskCategory
    {
        public TaskCategory()
        {
            this.Tasks = new HashSet<Task>();
            this.TaskCategoryForOrganisations = new HashSet<TaskCategoryForOrganisation>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Disabled { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string ColourName { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<TaskCategoryForOrganisation> TaskCategoryForOrganisations { get; set; }
    }
}
