//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerVehicle
    {
        public TrainerVehicle()
        {
            this.TrainerVehicleNotes = new HashSet<TrainerVehicleNote>();
            this.TrainerVehicleRemoves = new HashSet<TrainerVehicleRemove>();
            this.TrainerVehicleCategories = new HashSet<TrainerVehicleCategory>();
        }
    
        public int Id { get; set; }
        public int TrainerId { get; set; }
        public int VehicleTypeId { get; set; }
        public string NumberPlate { get; set; }
        public string Description { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int AddedByUserId { get; set; }
    
        public virtual Trainer Trainer { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual ICollection<TrainerVehicleNote> TrainerVehicleNotes { get; set; }
        public virtual ICollection<TrainerVehicleRemove> TrainerVehicleRemoves { get; set; }
        public virtual ICollection<TrainerVehicleCategory> TrainerVehicleCategories { get; set; }
        public virtual User User { get; set; }
    }
}
