//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerPreviousId
    {
        public int Id { get; set; }
        public int TrainerId { get; set; }
        public int PreviousTrainerId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> PreviousOrgId { get; set; }
        public Nullable<int> PreviousRgnId { get; set; }
    
        public virtual Trainer Trainer { get; set; }
    }
}
