//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        public Trainer()
        {
            this.CourseTrainer = new HashSet<CourseTrainer>();
            this.TrainerCourseType = new HashSet<TrainerCourseType>();
            this.TrainerEmail = new HashSet<TrainerEmail>();
            this.TrainerLicence = new HashSet<TrainerLicence>();
            this.TrainerLocation = new HashSet<TrainerLocation>();
            this.TrainerNote = new HashSet<TrainerNote>();
            this.TrainerOrganisation = new HashSet<TrainerOrganisation>();
            this.TrainerPhone = new HashSet<TrainerPhone>();
            this.TrainerCourseTypeCategories = new HashSet<TrainerCourseTypeCategory>();
            this.TrainerDatesUnavailables = new HashSet<TrainerDatesUnavailable>();
            this.TrainerWeekDaysAvailables = new HashSet<TrainerWeekDaysAvailable>();
            this.CourseDateTrainerAttendances = new HashSet<CourseDateTrainerAttendance>();
            this.TrainerSettings = new HashSet<TrainerSetting>();
            this.TrainerDocuments = new HashSet<TrainerDocument>();
            this.CourseDateClientAttendances = new HashSet<CourseDateClientAttendance>();
            this.DORSTrainers = new HashSet<DORSTrainer>();
            this.TrainerAvailabilities = new HashSet<TrainerAvailability>();
            this.TrainerAvailabilityByMonths = new HashSet<TrainerAvailabilityByMonth>();
            this.TrainerVenues = new HashSet<TrainerVenue>();
            this.TrainerAvailabilityDates = new HashSet<TrainerAvailabilityDate>();
            this.TrainerBookingRequests = new HashSet<TrainerBookingRequest>();
            this.TrainerInstructorRoles = new HashSet<TrainerInstructorRole>();
            this.TrainerVehicles = new HashSet<TrainerVehicle>();
            this.TrainerBookingLimitationByMonths = new HashSet<TrainerBookingLimitationByMonth>();
            this.TrainerBookingSummaries = new HashSet<TrainerBookingSummary>();
            this.TrainerBookingLimitationByYears = new HashSet<TrainerBookingLimitationByYear>();
            this.TrainerGrades = new HashSet<TrainerGrade>();
            this.TrainerInsurances = new HashSet<TrainerInsurance>();
            this.TaskRelatedToTrainers = new HashSet<TaskRelatedToTrainer>();
            this.TrainerPreviousIds = new HashSet<TrainerPreviousId>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string OtherNames { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public bool Locked { get; set; }
        public string PictureName { get; set; }
        public string OrganistionTitle { get; set; }
        public string OrganistionLocation { get; set; }
        public Nullable<int> UserId { get; set; }
        public int GenderId { get; set; }
        public Nullable<int> TrainerDupId { get; set; }
    
        public virtual ICollection<CourseTrainer> CourseTrainer { get; set; }
        public virtual ICollection<TrainerCourseType> TrainerCourseType { get; set; }
        public virtual ICollection<TrainerEmail> TrainerEmail { get; set; }
        public virtual ICollection<TrainerLicence> TrainerLicence { get; set; }
        public virtual ICollection<TrainerLocation> TrainerLocation { get; set; }
        public virtual ICollection<TrainerNote> TrainerNote { get; set; }
        public virtual ICollection<TrainerOrganisation> TrainerOrganisation { get; set; }
        public virtual ICollection<TrainerPhone> TrainerPhone { get; set; }
        public virtual ICollection<TrainerCourseTypeCategory> TrainerCourseTypeCategories { get; set; }
        public virtual ICollection<TrainerDatesUnavailable> TrainerDatesUnavailables { get; set; }
        public virtual ICollection<TrainerWeekDaysAvailable> TrainerWeekDaysAvailables { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<CourseDateTrainerAttendance> CourseDateTrainerAttendances { get; set; }
        public virtual ICollection<TrainerSetting> TrainerSettings { get; set; }
        public virtual ICollection<TrainerDocument> TrainerDocuments { get; set; }
        public virtual ICollection<CourseDateClientAttendance> CourseDateClientAttendances { get; set; }
        public virtual ICollection<DORSTrainer> DORSTrainers { get; set; }
        public virtual ICollection<TrainerAvailability> TrainerAvailabilities { get; set; }
        public virtual ICollection<TrainerAvailabilityByMonth> TrainerAvailabilityByMonths { get; set; }
        public virtual ICollection<TrainerVenue> TrainerVenues { get; set; }
        public virtual ICollection<TrainerAvailabilityDate> TrainerAvailabilityDates { get; set; }
        public virtual ICollection<TrainerBookingRequest> TrainerBookingRequests { get; set; }
        public virtual ICollection<TrainerInstructorRole> TrainerInstructorRoles { get; set; }
        public virtual ICollection<TrainerVehicle> TrainerVehicles { get; set; }
        public virtual ICollection<TrainerBookingLimitationByMonth> TrainerBookingLimitationByMonths { get; set; }
        public virtual ICollection<TrainerBookingSummary> TrainerBookingSummaries { get; set; }
        public virtual ICollection<TrainerBookingLimitationByYear> TrainerBookingLimitationByYears { get; set; }
        public virtual ICollection<TrainerGrade> TrainerGrades { get; set; }
        public virtual ICollection<TrainerInsurance> TrainerInsurances { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TaskRelatedToTrainer> TaskRelatedToTrainers { get; set; }
        public virtual ICollection<TrainerPreviousId> TrainerPreviousIds { get; set; }
    }
}
