//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerGrade
    {
        public int Id { get; set; }
        public int TrainerId { get; set; }
        public int Grade { get; set; }
        public string ADINumber { get; set; }
        public string FleetNumber { get; set; }
        public Nullable<System.DateTime> FleetRenewalDate { get; set; }
        public Nullable<System.DateTime> LastCheckTestDate { get; set; }
    
        public virtual Trainer Trainer { get; set; }
    }
}
