//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerAvailability
    {
        public int Id { get; set; }
        public Nullable<int> TrainerId { get; set; }
        public Nullable<bool> AvailableForFutureBookings { get; set; }
        public Nullable<bool> AvailableBetweenDates { get; set; }
        public Nullable<System.DateTime> FirstAvailableDate { get; set; }
        public Nullable<System.DateTime> LastAvailableDate { get; set; }
    
        public virtual Trainer Trainer { get; set; }
    }
}
