//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerVehicleRemove
    {
        public int Id { get; set; }
        public int TrainerVehicleId { get; set; }
        public System.DateTime DateRemoved { get; set; }
        public int RemovedByUserId { get; set; }
    
        public virtual TrainerVehicle TrainerVehicle { get; set; }
        public virtual User User { get; set; }
    }
}
