//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TriggerLog
    {
        public int Id { get; set; }
        public System.DateTime DateTimeRun { get; set; }
        public string TableName { get; set; }
        public string TriggerName { get; set; }
        public Nullable<int> InsertedTableRows { get; set; }
        public Nullable<int> DeletedTableRows { get; set; }
    }
}
