//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFeedback
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string IPAddress { get; set; }
        public string CurrentUrl { get; set; }
        public string PageIdentifier { get; set; }
        public string UserAgent { get; set; }
        public string OS { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public Nullable<bool> ResponseRequired { get; set; }
        public string Email { get; set; }
        public Nullable<bool> MessageSent { get; set; }
        public string RepliedBy { get; set; }
        public Nullable<System.DateTime> RepliedDate { get; set; }
        public string AdditionalInfo { get; set; }
    
        public virtual User User { get; set; }
    }
}
