//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenueImageMap
    {
        public int Id { get; set; }
        public int VenueId { get; set; }
        public int DocumentId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int AddedByUserId { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Venue Venue { get; set; }
        public virtual User User { get; set; }
    }
}
