//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenueDORSValidationRequest
    {
        public int Id { get; set; }
        public int VenueId { get; set; }
        public System.DateTime DateValidationRequested { get; set; }
        public bool RequestSubmittedToDORS { get; set; }
        public Nullable<System.DateTime> DateRequestSubmitted { get; set; }
        public bool DORSValidatedVenue { get; set; }
        public Nullable<System.DateTime> DateValidated { get; set; }
        public bool DORSRejectedValidation { get; set; }
        public Nullable<System.DateTime> DateRejected { get; set; }
    
        public virtual Venue Venue { get; set; }
    }
}
