//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public Venue()
        {
            this.VenueAddress = new HashSet<VenueAddress>();
            this.VenueCost = new HashSet<VenueCost>();
            this.VenueCourseType = new HashSet<VenueCourseType>();
            this.VenueDirections = new HashSet<VenueDirections>();
            this.CourseVenue = new HashSet<CourseVenue>();
            this.VenueEmail = new HashSet<VenueEmail>();
            this.VenueLocales = new HashSet<VenueLocale>();
            this.VenueRegions = new HashSet<VenueRegion>();
            this.CourseStencils = new HashSet<CourseStencil>();
            this.VenueImageMaps = new HashSet<VenueImageMap>();
            this.TrainerVenues = new HashSet<TrainerVenue>();
            this.CourseVenueEmails = new HashSet<CourseVenueEmail>();
            this.DORSSiteVenues = new HashSet<DORSSiteVenue>();
            this.VenueDORSValidationRequests = new HashSet<VenueDORSValidationRequest>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string Prefix { get; set; }
        public int OrganisationId { get; set; }
        public bool Enabled { get; set; }
        public string Code { get; set; }
        public bool DORSVenue { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual ICollection<VenueAddress> VenueAddress { get; set; }
        public virtual ICollection<VenueCost> VenueCost { get; set; }
        public virtual ICollection<VenueCourseType> VenueCourseType { get; set; }
        public virtual ICollection<VenueDirections> VenueDirections { get; set; }
        public virtual ICollection<CourseVenue> CourseVenue { get; set; }
        public virtual ICollection<VenueEmail> VenueEmail { get; set; }
        public virtual ICollection<VenueLocale> VenueLocales { get; set; }
        public virtual ICollection<VenueRegion> VenueRegions { get; set; }
        public virtual ICollection<CourseStencil> CourseStencils { get; set; }
        public virtual ICollection<VenueImageMap> VenueImageMaps { get; set; }
        public virtual ICollection<TrainerVenue> TrainerVenues { get; set; }
        public virtual ICollection<CourseVenueEmail> CourseVenueEmails { get; set; }
        public virtual ICollection<DORSSiteVenue> DORSSiteVenues { get; set; }
        public virtual ICollection<VenueDORSValidationRequest> VenueDORSValidationRequests { get; set; }
    }
}
