//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBlockedIP
    {
        public int Id { get; set; }
        public string BlockedIp { get; set; }
        public System.DateTime DateBlocked { get; set; }
        public Nullable<bool> BlockDisabled { get; set; }
        public string CreatedBy { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<int> BlockDisabledByUserId { get; set; }
        public string Comments { get; set; }
    }
}
