//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCalendarDatesByMonth
    {
        public Nullable<int> TheYear { get; set; }
        public int TheMonth { get; set; }
        public string DateRowLetter { get; set; }
        public int DateRowNumber { get; set; }
        public Nullable<System.DateTime> DateColumn1 { get; set; }
        public Nullable<System.DateTime> DateColumn2 { get; set; }
        public Nullable<System.DateTime> DateColumn3 { get; set; }
        public Nullable<System.DateTime> DateColumn4 { get; set; }
        public Nullable<System.DateTime> DateColumn5 { get; set; }
        public Nullable<System.DateTime> DateColumn6 { get; set; }
        public Nullable<System.DateTime> DateColumn7 { get; set; }
    }
}
