//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClientsUnableToUpdateInDOR
    {
        public int OrganisationId { get; set; }
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public string LicenceNumber { get; set; }
        public int CourseId { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public int CourseTypeId { get; set; }
        public string CourseTypeTitle { get; set; }
        public Nullable<int> TransferredFromCourseId { get; set; }
        public string PossibleReason { get; set; }
        public System.DateTime DateAndTimeRefreshed { get; set; }
    }
}
