//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClientPhoneRow
    {
        public int ClientId { get; set; }
        public string ClientMainPhoneNumber { get; set; }
        public int ClientMainPhoneTypeId { get; set; }
        public string ClientMainPhoneType { get; set; }
        public string ClientSecondPhoneNumber { get; set; }
        public Nullable<int> ClientSecondPhoneTypeId { get; set; }
        public string ClientSecondPhoneType { get; set; }
        public string ClientOtherPhoneNumbers { get; set; }
    }
}
