//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClientDORSDataLatest
    {
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> ReferringAuthorityId { get; set; }
        public Nullable<System.DateTime> DateReferred { get; set; }
        public Nullable<int> DORSAttendanceRef { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int DORSSchemeId { get; set; }
        public Nullable<bool> DataValidatedAgainstDORS { get; set; }
        public Nullable<int> DORSAttendanceStateId { get; set; }
        public bool IsMysteryShopper { get; set; }
    }
}
