//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClientsWithinCourse
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public int CourseId { get; set; }
        public string CourseReference { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public string CourseType { get; set; }
        public string CourseTypeCategory { get; set; }
        public Nullable<bool> CourseLocked { get; set; }
        public Nullable<bool> CourseProfileUneditable { get; set; }
        public int ClientId { get; set; }
        public string ClientTitle { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> ClientDateOfBirth { get; set; }
        public System.DateTime DateClientAdded { get; set; }
        public string ClientAddedByUser { get; set; }
        public string ClientPoliceReference { get; set; }
        public string ClientOtherReference { get; set; }
        public Nullable<bool> DORSCourse { get; set; }
        public Nullable<System.DateTime> ClientLastPaymentDate { get; set; }
        public Nullable<decimal> ClientLastPaymentAmount { get; set; }
        public Nullable<decimal> TotalAmountPaidByClient { get; set; }
        public Nullable<decimal> TotalAmountPaidByAllOnCourse { get; set; }
        public Nullable<decimal> ClientAmountOutstanding { get; set; }
        public Nullable<bool> OnlineBooking { get; set; }
    }
}
