//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClientPayment
    {
        public Nullable<int> OrganisationId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ClientName { get; set; }
        public System.DateTime PaymentTransactionDate { get; set; }
        public decimal PaymentAmount { get; set; }
        public string PaymentType { get; set; }
        public string PaymentMethod { get; set; }
        public string ReceiptNumber { get; set; }
        public int CreatedByUserId { get; set; }
        public string CreatedByUserName { get; set; }
        public string PaymentNote { get; set; }
    }
}
