//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClientsWithMissingDORSDataSummary
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public Nullable<int> TotalCreatedToday { get; set; }
        public Nullable<int> TotalCreatedYesterday { get; set; }
        public Nullable<int> TotalCreatedThisWeek { get; set; }
        public Nullable<int> TotalCreatedThisMonth { get; set; }
        public Nullable<int> TotalCreatedLastMonth { get; set; }
        public Nullable<int> TotalCreatedThisYear { get; set; }
        public Nullable<int> TotalCreatedBeforeThisYear { get; set; }
    }
}
