//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClientsMarkedForDeletion
    {
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public int RequestedByUserId { get; set; }
        public string RequestedByUserName { get; set; }
        public System.DateTime DateRequested { get; set; }
        public System.DateTime DeleteAfterDate { get; set; }
        public string Note { get; set; }
        public int OrganisationId { get; set; }
        public System.DateTime ClientCreatedDate { get; set; }
        public string LicenceNumber { get; set; }
    }
}
