//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClientDetail
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public int ClientId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string OtherNames { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public System.DateTime ClientCreatedDate { get; set; }
        public Nullable<int> LockedByUserId { get; set; }
        public string LockedByUserName { get; set; }
        public Nullable<System.DateTime> DateTimeLocked { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public string LicenceNumber { get; set; }
        public Nullable<System.DateTime> LicenceExpiryDate { get; set; }
        public Nullable<System.DateTime> LicencePhotoCardExpiryDate { get; set; }
        public string DrivingLicenceTypeName { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string ReferralReference { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string CourseStartTime { get; set; }
        public string CourseEndTime { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public Nullable<System.DateTime> CourseEndDate { get; set; }
        public Nullable<System.DateTime> CourseStartDate2 { get; set; }
        public string CourseStartTime2 { get; set; }
        public Nullable<System.DateTime> CourseEndDate2 { get; set; }
        public string CourseEndTime2 { get; set; }
        public Nullable<System.DateTime> CourseStartDate3 { get; set; }
        public string CourseStartTime3 { get; set; }
        public Nullable<System.DateTime> CourseEndDate3 { get; set; }
        public string CourseEndTime3 { get; set; }
        public string CourseReference { get; set; }
        public string CourseType { get; set; }
        public Nullable<decimal> CourseFee { get; set; }
        public string CourseTypeCategory { get; set; }
        public Nullable<int> ReferringAuthorityId { get; set; }
        public string ReferringAuthority { get; set; }
        public Nullable<System.DateTime> DateBooked { get; set; }
        public Nullable<int> VenueId { get; set; }
        public string VenueName { get; set; }
        public string VenueAddress { get; set; }
        public string VenuePostCode { get; set; }
        public string VenueDirection { get; set; }
        public Nullable<decimal> AmountPaidByClient { get; set; }
        public Nullable<decimal> TotalPaymentDueByClient { get; set; }
        public Nullable<System.DateTime> CoursePaymentDueDate { get; set; }
        public Nullable<bool> IsMysteryShopper { get; set; }
        public Nullable<bool> StillOnCourse { get; set; }
        public Nullable<System.DateTime> DORSExpiryDate { get; set; }
        public string SpecialRequirements { get; set; }
        public Nullable<System.DateTime> LastDateForCourseBooking { get; set; }
    }
}
