//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClientCourseBasicData
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> DORSIdentifier { get; set; }
        public string ClientName { get; set; }
        public System.DateTime ClientCreatedDate { get; set; }
        public string PostCode { get; set; }
        public string LicenceNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string ReferralReference { get; set; }
        public int ReferringAuthorityId { get; set; }
        public string ReferringAuthority { get; set; }
        public int CourseId { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public string CourseReference { get; set; }
        public int CourseTypeId { get; set; }
        public string CourseType { get; set; }
        public string CourseTypeCode { get; set; }
        public int VenueId { get; set; }
        public string Venue { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string Region { get; set; }
        public Nullable<decimal> AmountPaidByClient { get; set; }
    }
}
