//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCourseClientDORSAttendanceReadyForSending
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public int CourseId { get; set; }
        public string CourseReference { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public Nullable<System.DateTime> CourseEndDate { get; set; }
        public int CourseClientId { get; set; }
        public Nullable<int> NumberOfCourseDates { get; set; }
        public Nullable<int> NumberOfDatesAttenedByClient { get; set; }
        public Nullable<bool> CourseClientAttenedAllCourseDates { get; set; }
        public Nullable<int> CourseClientDORSAttendanceStateIdentifier { get; set; }
        public Nullable<int> DORSClientAttendanceIdentifier { get; set; }
        public Nullable<bool> Attended { get; set; }
        public Nullable<int> NewDORSAttendanceStateIdentifier { get; set; }
    }
}
