//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCourseInterpreterCount_SubView
    {
        public int OrganisationId { get; set; }
        public int CourseId { get; set; }
        public Nullable<int> NumberOfInterpretersBookedOnCourse { get; set; }
        public int InterpreterId { get; set; }
        public Nullable<long> InterpreterNumber { get; set; }
    }
}
