//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCourseTypeDetail
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public int Id { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int DaysBeforeCourseLastBooking { get; set; }
        public bool Disabled { get; set; }
        public bool DORSOnly { get; set; }
        public Nullable<decimal> CourseFee { get; set; }
        public Nullable<decimal> BookingSupplement { get; set; }
        public Nullable<int> PaymentDays { get; set; }
        public Nullable<int> MaxAttendeesWithZeroTrainers { get; set; }
        public Nullable<int> MaxAttendeesWithOneTrainer { get; set; }
        public Nullable<int> MaxAttendeesWithTwoTrainers { get; set; }
        public Nullable<int> MaxAttendeesWithThreeTrainers { get; set; }
        public Nullable<int> MaxAttendeesWithFourTrainers { get; set; }
        public string AdditionalInformation { get; set; }
        public int MaxTheoryTrainers { get; set; }
        public int MaxPracticalTrainers { get; set; }
    }
}
