//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCourseInterpreter
    {
        public int OrganisationId { get; set; }
        public int CourseId { get; set; }
        public int CourseTypeId { get; set; }
        public Nullable<int> CourseTypeCategoryId { get; set; }
        public string CourseTypeCategory { get; set; }
        public string CourseReference { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public Nullable<System.DateTime> CourseEndDate { get; set; }
        public int NumberOfBookedClients { get; set; }
        public int NumberOfTrainersBookedOnCourse { get; set; }
        public Nullable<int> VenueId { get; set; }
        public string VenueName { get; set; }
        public Nullable<bool> CourseAvailable { get; set; }
        public Nullable<bool> CancelledCourse { get; set; }
        public Nullable<int> InterpreterId { get; set; }
        public string InterpreterName { get; set; }
        public Nullable<int> InterpreterGenderId { get; set; }
        public string InterpreterGender { get; set; }
        public string InterpreterOneOf { get; set; }
        public Nullable<bool> InterpreterForTheory { get; set; }
        public Nullable<bool> InterpreterForPractical { get; set; }
        public Nullable<bool> InterpreterForTheoryAndPractical { get; set; }
        public string InterpreterLanguageList { get; set; }
    }
}
