//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCourseTrainerClientAttendance
    {
        public int OrganisationId { get; set; }
        public int CourseId { get; set; }
        public string CourseType { get; set; }
        public int CourseTypeId { get; set; }
        public Nullable<int> CourseTypeCategoryId { get; set; }
        public string CourseTypeCategory { get; set; }
        public string CourseReference { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int NumberOfBookedClients { get; set; }
        public Nullable<int> NumberOfTrainersBookedOnCourse { get; set; }
        public int VenueId { get; set; }
        public string VenueName { get; set; }
        public Nullable<bool> CourseAvailable { get; set; }
        public Nullable<bool> CourseCancelled { get; set; }
        public Nullable<bool> AttendanceCheckRequired { get; set; }
        public Nullable<System.DateTime> DateAttendanceSentToDORS { get; set; }
        public Nullable<bool> AttendanceSentToDORS { get; set; }
        public Nullable<bool> AttendanceCheckVerified { get; set; }
        public int TrainerId { get; set; }
        public string TrainerName { get; set; }
        public int GenderId { get; set; }
        public string Gender { get; set; }
        public string TrainerEmail { get; set; }
        public string TrainerAddress { get; set; }
        public string TrainerPostCode { get; set; }
        public string TrainerOneOf { get; set; }
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public Nullable<bool> ClientAttended { get; set; }
        public string SortColumn { get; set; }
    }
}
