//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCourseListPast
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public int CourseId { get; set; }
        public string CourseReference { get; set; }
        public int CourseTypeId { get; set; }
        public string CourseType { get; set; }
        public string CourseTypeCode { get; set; }
        public string CourseIdentity { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public Nullable<System.DateTime> CourseEndDate { get; set; }
    }
}
