//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCourseTypeCategoryRebookingActiveConditionNumber
    {
        public int OrganisationId { get; set; }
        public int CourseTypeId { get; set; }
        public int CourseTypeCategoryId { get; set; }
        public Nullable<int> ConditionNumber { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
    }
}
