//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCourseInterpretersWithoutEmail
    {
        public int OrganisationId { get; set; }
        public int CourseId { get; set; }
        public string CourseType { get; set; }
        public int CourseTypeId { get; set; }
        public Nullable<int> CourseTypeCategoryId { get; set; }
        public string CourseTypeCategory { get; set; }
        public string CourseReference { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public Nullable<System.DateTime> CourseEndDate { get; set; }
        public int InterpreterId { get; set; }
        public string InterpreterName { get; set; }
        public int InterpreterGenderId { get; set; }
        public string InterpreterGender { get; set; }
        public string InterpreterAddress { get; set; }
        public string InterpreterPostCode { get; set; }
        public string InterpreterMainPhoneNumber { get; set; }
        public Nullable<int> InterpreterMainPhoneTypeId { get; set; }
        public string InterpreterMainPhoneType { get; set; }
        public string InterpreterSecondPhoneNumber { get; set; }
        public Nullable<int> InterpreterSecondPhoneTypeId { get; set; }
        public string InterpreterSecondPhoneType { get; set; }
        public Nullable<System.DateTime> InterpreterDateOfBirth { get; set; }
    }
}
