//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCourseTrainersWithoutEmail
    {
        public int OrganisationId { get; set; }
        public int CourseId { get; set; }
        public string CourseType { get; set; }
        public int CourseTypeId { get; set; }
        public Nullable<int> CourseTypeCategoryId { get; set; }
        public string CourseTypeCategory { get; set; }
        public string CourseReference { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public Nullable<System.DateTime> CourseEndDate { get; set; }
        public int TrainerId { get; set; }
        public string TrainerName { get; set; }
        public int TrainerGenderId { get; set; }
        public string TrainerGender { get; set; }
        public string TrainerAddress { get; set; }
        public string TrainerPostCode { get; set; }
        public string TrainerMainPhoneNumber { get; set; }
        public Nullable<int> TrainerMainPhoneTypeId { get; set; }
        public string TrainerMainPhoneType { get; set; }
        public string TrainerSecondPhoneNumber { get; set; }
        public Nullable<int> TrainerSecondPhoneTypeId { get; set; }
        public string TrainerSecondPhoneType { get; set; }
        public Nullable<System.DateTime> TrainerDateOfBirth { get; set; }
    }
}
