//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCoursesWithMissingAttendance
    {
        public int OrganisationId { get; set; }
        public int CourseId { get; set; }
        public int CourseTypeId { get; set; }
        public string CourseTypeTitle { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public Nullable<System.DateTime> CourseEndDate { get; set; }
        public int TrainerId { get; set; }
        public string TrainerName { get; set; }
        public string TrainerMobileNumber { get; set; }
        public string TrainerHomeNumber { get; set; }
        public string TrainerWorkNumber { get; set; }
        public string TrainerEmail { get; set; }
    }
}
