//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCourseTrainer
    {
        public int OrganisationId { get; set; }
        public int CourseId { get; set; }
        public string CourseType { get; set; }
        public int CourseTypeId { get; set; }
        public Nullable<int> CourseTypeCategoryId { get; set; }
        public string CourseTypeCategory { get; set; }
        public string CourseReference { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int NumberOfBookedClients { get; set; }
        public Nullable<int> NumberOfTrainersBookedOnCourse { get; set; }
        public Nullable<int> VenueId { get; set; }
        public string VenueName { get; set; }
        public Nullable<bool> CourseAvailable { get; set; }
        public Nullable<bool> CourseCancelled { get; set; }
        public Nullable<bool> CourseLocked { get; set; }
        public Nullable<bool> CourseProfileUneditable { get; set; }
        public string CourseTrainerRefenece { get; set; }
        public Nullable<decimal> CourseTrainerPaymentDue { get; set; }
        public string CourseTrainerSessionBooking { get; set; }
        public Nullable<bool> AttendanceCheckRequired { get; set; }
        public Nullable<System.DateTime> DateAttendanceSentToDORS { get; set; }
        public Nullable<bool> AttendanceSentToDORS { get; set; }
        public Nullable<bool> AttendanceCheckVerified { get; set; }
        public int TrainerId { get; set; }
        public string DORSTrainerIdentifier { get; set; }
        public string TrainerName { get; set; }
        public int GenderId { get; set; }
        public string Gender { get; set; }
        public string TrainerOneOf { get; set; }
        public bool TrainerForTheory { get; set; }
        public bool TrainerForPractical { get; set; }
        public Nullable<bool> TrainerForTheoryAndPractical { get; set; }
        public double TrainerDistanceToVenueInMiles { get; set; }
        public int TrainerDistanceToVenueInMilesRounded { get; set; }
    }
}
