//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDashboardMeter_DORSOfferWithdrawn
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public System.DateTime DateAndTimeRefreshed { get; set; }
        public int TotalCreatedToday { get; set; }
        public int TotalCreatedYesterday { get; set; }
        public int TotalCreatedThisWeek { get; set; }
        public int TotalCreatedThisMonth { get; set; }
        public int TotalCreatedPreviousMonth { get; set; }
        public int TotalCreatedTwoMonthsAgo { get; set; }
    }
}
