//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDashboardMeter_Email
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public System.DateTime DateAndTimeRefreshed { get; set; }
        public int EmailsSentToday { get; set; }
        public int EmailsSentYesterday { get; set; }
        public int EmailsSentThisMonth { get; set; }
        public int EmailsSentLastMonth { get; set; }
        public int ScheduledEmails { get; set; }
    }
}
