//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDataViewColumnAvailabilityAndUse
    {
        public int DataViewId { get; set; }
        public string DataViewTitle { get; set; }
        public string DataViewName { get; set; }
        public Nullable<int> LetterCategoryId { get; set; }
        public string LetterCategoryCode { get; set; }
        public string LetterCategoryTitle { get; set; }
        public string LetterCategoryIdKeyName { get; set; }
        public string DataViewColumnName { get; set; }
        public string DataViewColumnTitle { get; set; }
        public string DataViewColumnDataType { get; set; }
        public string LetterTagName { get; set; }
    }
}
