//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDashboardMeter_UserAccess
    {
        public int UserId { get; set; }
        public string UserDisplayName { get; set; }
        public Nullable<int> DashboardMeterId { get; set; }
        public string DashboardMeterName { get; set; }
        public string DashboardMeterTitle { get; set; }
        public string DashboardMeterDescription { get; set; }
        public Nullable<int> DashboardMeterRefreshRate { get; set; }
        public string DashboardMeterCategory { get; set; }
        public Nullable<int> DashboardMeterCategoryId { get; set; }
        public string DashboardMeterCategoryPicture { get; set; }
    }
}
