//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDashboardMeter_Clients
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public System.DateTime DateAndTimeRefreshed { get; set; }
        public int TotalClients { get; set; }
        public int RegisteredOnlineToday { get; set; }
        public int RegisteredToday { get; set; }
        public int RegisteredOnlineYesterday { get; set; }
        public int RegisteredYesterday { get; set; }
        public int NumberOfUnpaidCourses { get; set; }
        public decimal TotalAmountUnpaid { get; set; }
        public int ClientsWithRequirementsRegisteredOnlineToday { get; set; }
        public int TotalUpcomingClientsWithRequirements { get; set; }
        public int UnableToUpdateInDORS { get; set; }
        public int AttendanceNotUploadedToDORS { get; set; }
        public int ClientsWithMissingReferringAuthorityCreatedThisWeek { get; set; }
        public int ClientsWithMissingReferringAuthorityCreatedThisMonth { get; set; }
        public int ClientsWithMissingReferringAuthorityCreatedLastMonth { get; set; }
    }
}
