//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDashboardMeter_Payments
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public System.DateTime DateAndTimeRefreshed { get; set; }
        public int NumberOfPaymentsTakenToday { get; set; }
        public int NumberOfPaymentsTakenYesterday { get; set; }
        public int NumberOfPaymentsTakenThisWeek { get; set; }
        public int NumberOfPaymentsTakenThisMonth { get; set; }
        public int NumberOfPaymentsTakenPreviousMonth { get; set; }
        public int NumberOfPaymentsTakenThisYear { get; set; }
        public int NumberOfPaymentsTakenPreviousYear { get; set; }
        public int NumberOfOnlinePaymentsTakenToday { get; set; }
        public int NumberOfOnlinePaymentsTakenYesterday { get; set; }
        public int NumberOfOnlinePaymentsTakenThisWeek { get; set; }
        public int NumberOfOnlinePaymentsTakenThisMonth { get; set; }
        public int NumberOfOnlinePaymentsTakenPreviousMonth { get; set; }
        public int NumberOfOnlinePaymentsTakenThisYear { get; set; }
        public int NumberOfOnlinePaymentsTakenPreviousYear { get; set; }
        public int NumberOfUnallocatedPaymentsTakenToday { get; set; }
        public int NumberOfUnallocatedPaymentsTakenYesterday { get; set; }
        public int NumberOfUnallocatedPaymentsTakenThisWeek { get; set; }
        public int NumberOfUnallocatedPaymentsTakenThisMonth { get; set; }
        public int NumberOfUnallocatedPaymentsTakenPreviousMonth { get; set; }
        public int NumberOfUnallocatedPaymentsTakenThisYear { get; set; }
        public int NumberOfUnallocatedPaymentsTakenPreviousYear { get; set; }
        public int NumberOfRefundedPaymentsTakenToday { get; set; }
        public int NumberOfRefundedPaymentsTakenYesterday { get; set; }
        public int NumberOfRefundedPaymentsTakenThisWeek { get; set; }
        public int NumberOfRefundedPaymentsTakenThisMonth { get; set; }
        public int NumberOfRefundedPaymentsTakenPreviousMonth { get; set; }
        public int NumberOfRefundedPaymentsTakenThisYear { get; set; }
        public int NumberOfRefundedPaymentsTakenPreviousYear { get; set; }
        public decimal PaymentSumTakenToday { get; set; }
        public decimal PaymentSumTakenYesterday { get; set; }
        public decimal PaymentSumTakenThisWeek { get; set; }
        public decimal PaymentSumTakenThisMonth { get; set; }
        public decimal PaymentSumTakenPreviousMonth { get; set; }
        public decimal PaymentSumTakenThisYear { get; set; }
        public decimal PaymentSumTakenPreviousYear { get; set; }
        public int NumberOfPhonePaymentsTakenToday { get; set; }
        public int NumberOfPhonePaymentsTakenYesterday { get; set; }
        public int NumberOfPhonePaymentsTakenThisWeek { get; set; }
        public int NumberOfPhonePaymentsTakenThisMonth { get; set; }
        public int NumberOfPhonePaymentsTakenPreviousMonth { get; set; }
        public int NumberOfPhonePaymentsTakenThisYear { get; set; }
        public int NumberOfPhonePaymentsTakenPreviousYear { get; set; }
    }
}
