//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwInterpreterPhoneRow
    {
        public int Id { get; set; }
        public int InterpreterId { get; set; }
        public string InterpreterMainPhoneNumber { get; set; }
        public int InterpreterMainPhoneTypeId { get; set; }
        public string InterpreterMainPhoneType { get; set; }
        public string InterpreterSecondPhoneNumber { get; set; }
        public Nullable<int> InterpreterSecondPhoneTypeId { get; set; }
        public string InterpreterSecondPhoneType { get; set; }
    }
}
