//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLatestExpiringTrainerLicence
    {
        public int TrainerId { get; set; }
        public string LicenceNumber { get; set; }
        public Nullable<System.DateTime> LicenceExpiryDate { get; set; }
        public Nullable<int> DriverLicenceTypeId { get; set; }
        public Nullable<System.DateTime> LicencePhotoCardExpiryDate { get; set; }
        public Nullable<System.DateTime> LicenceCheckDue { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
