//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLetterTemplateDetail
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public Nullable<int> LetterTemplateId { get; set; }
        public int LetterCategoryId { get; set; }
        public string LetterCategoryCode { get; set; }
        public string LetterCategoryTitle { get; set; }
        public string LetterCategoryDescription { get; set; }
        public string LetterTemplateTitle { get; set; }
        public Nullable<int> LetterTemplateDocumentId { get; set; }
        public string LetterTemplateDocumentName { get; set; }
        public Nullable<int> LetterTemplateVersion { get; set; }
        public Nullable<System.DateTime> LetterTemplateDateChanged { get; set; }
    }
}
