//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwOrganisationPaymentCardTypeToPaymentMethodLink
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public Nullable<int> PaymentCardTypeId { get; set; }
        public string PaymentCardTypeName { get; set; }
        public int PaymentMethodId { get; set; }
        public string PaymentMethodName { get; set; }
    }
}
