//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPaymentDetail
    {
        public int PaymentId { get; set; }
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<bool> PaymentsToday { get; set; }
        public Nullable<bool> PaymentsYesterday { get; set; }
        public Nullable<bool> PaymentsThisWeek { get; set; }
        public Nullable<bool> PaymentsThisMonth { get; set; }
        public Nullable<bool> PaymentsPreviousMonth { get; set; }
        public Nullable<bool> PaymentsTwoMonthsAgo { get; set; }
        public Nullable<bool> PaymentsThisYear { get; set; }
        public Nullable<bool> PaymentsPreviousYear { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public string PaymentTypeName { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public string PaymentMethodName { get; set; }
        public decimal PaymentAmount { get; set; }
        public Nullable<bool> RefundPayment { get; set; }
        public Nullable<bool> CardPayment { get; set; }
        public string PaymentName { get; set; }
        public string PaymentReference { get; set; }
        public string PaymentAdditionalInfo { get; set; }
        public string PaymentReceiptNumber { get; set; }
        public string PaymentAuthCode { get; set; }
        public string PaymentNotes { get; set; }
        public int PaymentRecordedByUserId { get; set; }
        public string PaymentRecordedByUser { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> ClientDateOfBirth { get; set; }
        public string ClientPoliceReference { get; set; }
        public string ClientOtherReference { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string CourseType { get; set; }
        public Nullable<int> CourseTypeId { get; set; }
        public Nullable<int> CourseTypeCategoryId { get; set; }
        public string CourseTypeCategory { get; set; }
        public string CourseReference { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public Nullable<System.DateTime> CourseEndDate { get; set; }
        public string VenueTitle { get; set; }
        public string CourseAdditionalInfo { get; set; }
        public Nullable<bool> PaymentUnallocatedToClient { get; set; }
        public Nullable<int> RefundId { get; set; }
    }
}
