//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPaymentCardType
    {
        public int PaymentCardTypeId { get; set; }
        public string PaymentCardTypeName { get; set; }
        public string PaymentCardTypeDisplayName { get; set; }
        public bool PaymentCardTypeDisabled { get; set; }
        public Nullable<int> PaymentCardValidationTypeId { get; set; }
        public string PaymentCardValidationTypeName { get; set; }
    }
}
