//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPaymentsLinksDetail
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public int PaymentId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<bool> PaidByClientOnline { get; set; }
        public Nullable<bool> CreatedToday { get; set; }
        public Nullable<bool> CreatedYesterday { get; set; }
        public Nullable<bool> CreatedThisWeek { get; set; }
        public Nullable<bool> CreatedThisMonth { get; set; }
        public Nullable<bool> CreatedPreviousMonth { get; set; }
        public Nullable<bool> CreatedTwoMonthsAgo { get; set; }
        public Nullable<bool> CreatedThisYear { get; set; }
        public Nullable<bool> CreatedPreviousYear { get; set; }
        public decimal PaymentAmount { get; set; }
        public Nullable<bool> RefundPayment { get; set; }
        public Nullable<bool> CardPayment { get; set; }
        public string PaymentName { get; set; }
        public string PaymentReference { get; set; }
        public Nullable<bool> OnLinePayment { get; set; }
        public string PaymentAdditionalInfo { get; set; }
        public Nullable<int> ClientOrganisationId { get; set; }
        public string ClientOrganisationName { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> ClientDateOfBirth { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string CourseType { get; set; }
        public Nullable<int> CourseTypeId { get; set; }
        public Nullable<int> CourseTypeCategoryId { get; set; }
        public string CourseTypeCategory { get; set; }
        public string CourseReference { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public Nullable<System.DateTime> CourseEndDate { get; set; }
        public string VenueTitle { get; set; }
        public string CourseAdditionalInfo { get; set; }
        public Nullable<bool> PaymentUnallocatedToClient { get; set; }
    }
}
