//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReportsTrainerDetail
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public int TrainerId { get; set; }
        public string TrainerName { get; set; }
        public Nullable<System.DateTime> TraineDateOfBirth { get; set; }
        public int GenderId { get; set; }
        public string TrainerGender { get; set; }
        public string TrainerMainPhoneNumber { get; set; }
        public string TrainerMainPhoneType { get; set; }
        public string TrainerSecondPhoneNumber { get; set; }
        public string TrainerSecondPhoneType { get; set; }
        public string TrainerAddress { get; set; }
        public string TrainerPostCode { get; set; }
        public string TrainerLicenceNumber { get; set; }
        public Nullable<System.DateTime> TrainerLicenceExpiryDate { get; set; }
    }
}
