//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReconciliationData
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public int ReconciliationId { get; set; }
        public int ReconciliationConfigurationId { get; set; }
        public Nullable<System.DateTime> ReconciliationTransactionDate { get; set; }
        public Nullable<decimal> ReconciliationTransactionAmount { get; set; }
        public string ReconciliationReference1 { get; set; }
        public string ReconciliationReference2 { get; set; }
        public string ReconciliationReference3 { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<System.DateTime> PaymentTransactionDate { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string PaymentAuthCode { get; set; }
        public string ReceiptNumber { get; set; }
        public bool Duplicate { get; set; }
        public string ReconciliationDataComment { get; set; }
        public int ReconciliationDataId { get; set; }
    }
}
