//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReportsCourseType
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public int Id { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public bool Disabled { get; set; }
        public bool DORSOnly { get; set; }
        public int MaxTheoryTrainers { get; set; }
        public int MaxPracticalTrainers { get; set; }
    }
}
