//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReportDefault
    {
        public string ReportDefaultPageSize { get; set; }
        public string ReportDefaultPageOrientation { get; set; }
        public int ReportDefaultPortraitRowsPerPage { get; set; }
        public int ReportDefaultLanscapeRowsPerPage { get; set; }
        public int ReportMaximumRows { get; set; }
    }
}
