//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReportColumn
    {
        public int ReportId { get; set; }
        public string ReportTitle { get; set; }
        public string ReportDescription { get; set; }
        public bool AtlasSystemReport { get; set; }
        public bool LandscapeReport { get; set; }
        public int ReportDataGridId { get; set; }
        public int ReportDataViewId { get; set; }
        public string ReportDataViewName { get; set; }
        public int ColumnId { get; set; }
        public string ColumnName { get; set; }
        public string ColumnTitle { get; set; }
        public Nullable<int> ColumnDisplayOrder { get; set; }
        public Nullable<int> ColumnSortOrder { get; set; }
        public string ColumnDataType { get; set; }
    }
}
