//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReportParameterDataType
    {
        public Nullable<int> ReportId { get; set; }
        public int ReportDataGridId { get; set; }
        public Nullable<int> DataViewId { get; set; }
        public int DataViewColumnId { get; set; }
        public string DataViewName { get; set; }
        public string DataViewTitle { get; set; }
        public string DataType { get; set; }
        public string SelectIdentifier { get; set; }
        public string DataTypeName { get; set; }
        public int ReportDataTypeId { get; set; }
    }
}
