//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReportsByUser
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string ReportCategory { get; set; }
        public Nullable<bool> ReportCategoryDisabled { get; set; }
        public int ReportId { get; set; }
        public string ReportTitle { get; set; }
        public string ReportDescription { get; set; }
        public bool AtlasSystemReport { get; set; }
        public bool Landscape { get; set; }
        public int ReportVersion { get; set; }
    }
}
