//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReportsVenueDetail
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public int Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string ExtendedTitle { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string Prefix { get; set; }
        public bool Enabled { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string AdditionalInformation { get; set; }
        public bool DORSVenue { get; set; }
    }
}
