//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwScheduledEmail
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public string EmailServiceName { get; set; }
        public Nullable<System.DateTime> EmailCreatedDate { get; set; }
        public string EmailState { get; set; }
        public string EmailToAddress { get; set; }
        public string EmailReplyNameEmailCombo { get; set; }
        public string EmailContent { get; set; }
        public Nullable<bool> EmailCCFlag { get; set; }
        public Nullable<bool> EmailBCCFlag { get; set; }
        public string EmailAttachmentPath1 { get; set; }
        public string EmailAttachmentPath2 { get; set; }
        public string EmailAttachmentPath3 { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<System.DateTime> EmailDateSent { get; set; }
        public string EmailScheduledDate { get; set; }
    }
}
