//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSMSMessage
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public Nullable<int> SMSServiceId { get; set; }
        public string SMSServiceName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string SMSStatusName { get; set; }
        public string SMSToPhoneNumber { get; set; }
        public string SMSContent { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<System.DateTime> SMSDateSent { get; set; }
        public string SMSScheduledDate { get; set; }
    }
}
