//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSMSMessagesReadyToBeSent
    {
        public Nullable<int> SMSServiceId { get; set; }
        public string SMSServiceName { get; set; }
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public int SMSId { get; set; }
        public string Content { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> SendSMSAfter { get; set; }
        public string SMSDisplayName { get; set; }
    }
}
