//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSystemFeaturesWithinGroupsForUser
    {
        public Nullable<int> OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public int UserId { get; set; }
        public Nullable<int> SystemFeatureGroupId { get; set; }
        public string SystemFeatureGroupName { get; set; }
        public string SystemFeatureGroupTitle { get; set; }
        public string SystemFeatureGroupDescription { get; set; }
        public Nullable<bool> SystemFeatureGroupSystemAdministratorOnly { get; set; }
        public Nullable<bool> SystemFeatureGroupOrganisationAdministratorOnly { get; set; }
        public Nullable<bool> SystemFeatureGroupDisabled { get; set; }
        public Nullable<int> SystemFeatureId { get; set; }
        public string SystemFeatureName { get; set; }
        public string SystemFeatureTitle { get; set; }
        public string SystemFeatureDescription { get; set; }
        public Nullable<bool> SystemFeatureDisabled { get; set; }
        public string SystemFeatureNotes { get; set; }
    }
}
