//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSystemStatu
    {
        public bool SystemAvailable { get; set; }
        public string SystemStatus { get; set; }
        public string SystemStatusColour { get; set; }
        public string SystemBlockedMessage { get; set; }
        public string AtlasSystemName { get; set; }
        public string AtlasSystemCode { get; set; }
        public string AtlasSystemType { get; set; }
        public bool OnlineBookingSystemNoticeOn { get; set; }
        public string OnlineBookingSystemNoticeMessage { get; set; }
        public bool OnlineBookingSystemNoticeClickHereOn { get; set; }
        public string OnlineBookingSystemNoticeClickHereMessage { get; set; }
        public string OnlineBookingSystemNoticeClickHereLink { get; set; }
        public string OnlineBookingSystemNoticeColour { get; set; }
        public bool OnlineBookingBlocked { get; set; }
    }
}
