//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTaskSummaryByUser
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public bool ShowTaskList { get; set; }
        public bool AllowTaskCreation { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public string UserEmailAddress { get; set; }
        public int TaskPriorityNumber { get; set; }
        public Nullable<int> TotalNumberOfOpenTasks { get; set; }
        public Nullable<int> TotalNumberOfClosedTasks { get; set; }
    }
}
