//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTrainerSessionAvailabilityByMonth
    {
        public int TrainerId { get; set; }
        public Nullable<int> TheYear { get; set; }
        public int TheMonth { get; set; }
        public string DateRowLetter { get; set; }
        public int DateRowNumber { get; set; }
        public Nullable<System.DateTime> DateColumn1 { get; set; }
        public string TitleColumn1 { get; set; }
        public string Column1PreviousMonthDate { get; set; }
        public string Column1NextMonthDate { get; set; }
        public Nullable<bool> Column1FullyBooked { get; set; }
        public Nullable<bool> Column1PartiallyBooked { get; set; }
        public Nullable<bool> ShowColumn1Session1Available { get; set; }
        public Nullable<bool> ShowColumn1Session1Booked { get; set; }
        public Nullable<bool> ShowColumn1Session2Available { get; set; }
        public Nullable<bool> ShowColumn1Session2Booked { get; set; }
        public Nullable<bool> ShowColumn1Session3Available { get; set; }
        public Nullable<bool> ShowColumn1Session3Booked { get; set; }
        public Nullable<System.DateTime> DateColumn2 { get; set; }
        public string TitleColumn2 { get; set; }
        public string Column2PreviousMonthDate { get; set; }
        public string Column2NextMonthDate { get; set; }
        public Nullable<bool> Column2FullyBooked { get; set; }
        public Nullable<bool> Column2PartiallyBooked { get; set; }
        public Nullable<bool> ShowColumn2Session1Available { get; set; }
        public Nullable<bool> ShowColumn2Session1Booked { get; set; }
        public Nullable<bool> ShowColumn2Session2Available { get; set; }
        public Nullable<bool> ShowColumn2Session2Booked { get; set; }
        public Nullable<bool> ShowColumn2Session3Available { get; set; }
        public Nullable<bool> ShowColumn2Session3Booked { get; set; }
        public Nullable<System.DateTime> DateColumn3 { get; set; }
        public string TitleColumn3 { get; set; }
        public string Column3PreviousMonthDate { get; set; }
        public string Column3NextMonthDate { get; set; }
        public Nullable<bool> Column3FullyBooked { get; set; }
        public Nullable<bool> Column3PartiallyBooked { get; set; }
        public Nullable<bool> ShowColumn3Session1Available { get; set; }
        public Nullable<bool> ShowColumn3Session1Booked { get; set; }
        public Nullable<bool> ShowColumn3Session2Available { get; set; }
        public Nullable<bool> ShowColumn3Session2Booked { get; set; }
        public Nullable<bool> ShowColumn3Session3Available { get; set; }
        public Nullable<bool> ShowColumn3Session3Booked { get; set; }
        public Nullable<System.DateTime> DateColumn4 { get; set; }
        public string TitleColumn4 { get; set; }
        public string Column4PreviousMonthDate { get; set; }
        public string Column4NextMonthDate { get; set; }
        public Nullable<bool> Column4FullyBooked { get; set; }
        public Nullable<bool> Column4PartiallyBooked { get; set; }
        public Nullable<bool> ShowColumn4Session1Available { get; set; }
        public Nullable<bool> ShowColumn4Session1Booked { get; set; }
        public Nullable<bool> ShowColumn4Session2Available { get; set; }
        public Nullable<bool> ShowColumn4Session2Booked { get; set; }
        public Nullable<bool> ShowColumn4Session3Available { get; set; }
        public Nullable<bool> ShowColumn4Session3Booked { get; set; }
        public Nullable<System.DateTime> DateColumn5 { get; set; }
        public string TitleColumn5 { get; set; }
        public string Column5PreviousMonthDate { get; set; }
        public string Column5NextMonthDate { get; set; }
        public Nullable<bool> Column5FullyBooked { get; set; }
        public Nullable<bool> Column5PartiallyBooked { get; set; }
        public Nullable<bool> ShowColumn5Session1Available { get; set; }
        public Nullable<bool> ShowColumn5Session1Booked { get; set; }
        public Nullable<bool> ShowColumn5Session2Available { get; set; }
        public Nullable<bool> ShowColumn5Session2Booked { get; set; }
        public Nullable<bool> ShowColumn5Session3Available { get; set; }
        public Nullable<bool> ShowColumn5Session3Booked { get; set; }
        public Nullable<System.DateTime> DateColumn6 { get; set; }
        public string TitleColumn6 { get; set; }
        public string Column6PreviousMonthDate { get; set; }
        public string Column6NextMonthDate { get; set; }
        public Nullable<bool> Column6FullyBooked { get; set; }
        public Nullable<bool> Column6PartiallyBooked { get; set; }
        public Nullable<bool> ShowColumn6Session1Available { get; set; }
        public Nullable<bool> ShowColumn6Session1Booked { get; set; }
        public Nullable<bool> ShowColumn6Session2Available { get; set; }
        public Nullable<bool> ShowColumn6Session2Booked { get; set; }
        public Nullable<bool> ShowColumn6Session3Available { get; set; }
        public Nullable<bool> ShowColumn6Session3Booked { get; set; }
        public Nullable<System.DateTime> DateColumn7 { get; set; }
        public string TitleColumn7 { get; set; }
        public string Column7PreviousMonthDate { get; set; }
        public string Column7NextMonthDate { get; set; }
        public Nullable<bool> Column7FullyBooked { get; set; }
        public Nullable<bool> Column7PartiallyBooked { get; set; }
        public Nullable<bool> ShowColumn7Session1Available { get; set; }
        public Nullable<bool> ShowColumn7Session1Booked { get; set; }
        public Nullable<bool> ShowColumn7Session2Available { get; set; }
        public Nullable<bool> ShowColumn7Session2Booked { get; set; }
        public Nullable<bool> ShowColumn7Session3Available { get; set; }
        public Nullable<bool> ShowColumn7Session3Booked { get; set; }
    }
}
