//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTrainingSession
    {
        public int SessionNumber { get; set; }
        public string SessionTitle { get; set; }
        public string SessionStartTime { get; set; }
        public string SessionEndTime { get; set; }
    }
}
