//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTrainerVehicle
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public int TrainerId { get; set; }
        public string TrainerName { get; set; }
        public Nullable<System.DateTime> TrainerDateOfBirth { get; set; }
        public string TrainerLicenceNumber { get; set; }
        public int TrainerVehicleId { get; set; }
        public int VehicleTypeId { get; set; }
        public string VehicleTypeName { get; set; }
        public string VehicleTypeDescription { get; set; }
        public string TrainerVehicleNumberPlate { get; set; }
        public string TrainerVehicleDescription { get; set; }
        public System.DateTime TrainerVehicleDateAdded { get; set; }
        public int TrainerVehicleAddedByUserId { get; set; }
        public string TrainerVehicleNotes { get; set; }
        public string TrainerVehicleCategories { get; set; }
        public string TrainerVehicleCategoryIds { get; set; }
        public string TrainerVehicleDescriptionWithCategories { get; set; }
    }
}
