//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTrainersWithinPostalAreaAndDistrict
    {
        public Nullable<int> OrganisationId { get; set; }
        public string PostalArea { get; set; }
        public string PostalDistrict { get; set; }
        public int TrainerId { get; set; }
        public string TrainerName { get; set; }
        public Nullable<System.DateTime> TrainerDateofBirth { get; set; }
        public string TrainerGender { get; set; }
    }
}
