//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTrainersWithinCourse
    {
        public int OrganisationId { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public string CourseType { get; set; }
        public string CourseCategory { get; set; }
        public string CourseReference { get; set; }
        public int TrainerId { get; set; }
        public string TrainerName { get; set; }
        public Nullable<System.DateTime> TrainerAllocatedDate { get; set; }
        public Nullable<bool> CourseLocked { get; set; }
        public Nullable<bool> CourseProfileUneditable { get; set; }
    }
}
