//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTrainerAllocatedCourse
    {
        public int TrainerId { get; set; }
        public string TrainerName { get; set; }
        public int GenderId { get; set; }
        public string Gender { get; set; }
        public string LoginId { get; set; }
        public int CourseOrganisationId { get; set; }
        public string CourseOrganisationName { get; set; }
        public int CourseId { get; set; }
        public string CourseCancelled { get; set; }
        public string CourseType { get; set; }
        public int CourseTypeId { get; set; }
        public Nullable<int> CourseTypeCategoryId { get; set; }
        public string CourseTypeCategory { get; set; }
        public string CourseReference { get; set; }
        public Nullable<int> VenueId { get; set; }
        public string VenueTitle { get; set; }
        public string VenueDescription { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> MaximumVenuePlaces { get; set; }
        public Nullable<int> ReservedVenuePlaces { get; set; }
        public Nullable<int> PlacesRemaining { get; set; }
        public int NumberOfBookedClients { get; set; }
        public Nullable<bool> AttendanceCheckRequired { get; set; }
        public Nullable<System.DateTime> AttendanceLastUpdated { get; set; }
        public Nullable<bool> AttendanceCheckVerified { get; set; }
    }
}
