//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTrainerDefaultContactInformation
    {
        public int TrainerId { get; set; }
        public string TrainerName { get; set; }
        public Nullable<System.DateTime> TrainerDateOfBirth { get; set; }
        public Nullable<int> TrainerUserId { get; set; }
        public int TrainerGenderId { get; set; }
        public string TrainerGender { get; set; }
        public string TrainerEmail { get; set; }
        public string TrainerAddress { get; set; }
        public string TrainerPostCode { get; set; }
    }
}
