//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUserExtendedPermission
    {
        public int OrganisationId { get; set; }
        public string Organisation { get; set; }
        public int UserId { get; set; }
        public string LoginId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public bool AdhocReporting { get; set; }
        public bool ReportScheduling { get; set; }
        public bool InvoiceManagement { get; set; }
        public bool DataReconciliation { get; set; }
        public Nullable<bool> ShowNetcallFeatures { get; set; }
        public bool AllowManualEditingOfClientDORSData { get; set; }
        public bool ShowTaskList { get; set; }
        public bool AllowTaskCreation { get; set; }
    }
}
