//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUserDetail
    {
        public int OrganisationId { get; set; }
        public string Organisation { get; set; }
        public int UserId { get; set; }
        public string LoginId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsAdministrator { get; set; }
        public Nullable<bool> IsTrainer { get; set; }
        public Nullable<bool> IsOrgUser { get; set; }
        public Nullable<bool> IsSupportStaff { get; set; }
        public Nullable<bool> IsReferringAuthorityStaff { get; set; }
        public Nullable<bool> IsSystemAdministrator { get; set; }
        public Nullable<bool> IsClient { get; set; }
        public Nullable<bool> IsSystemAdminSupport { get; set; }
        public string ReferringAuthorityName { get; set; }
        public int GenderId { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> LastLoginAttempt { get; set; }
        public Nullable<System.DateTime> LastSuccessfulLogin { get; set; }
        public bool Disabled { get; set; }
        public string SecretQuestion { get; set; }
        public string SecretAnswer { get; set; }
        public bool PasswordChangeRequired { get; set; }
        public Nullable<bool> IsMysteryShopperAdministrator { get; set; }
        public Nullable<bool> SystemIsReadOnly { get; set; }
    }
}
