//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwVenuesWithNoRegionAssigned
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public int VenueId { get; set; }
        public string VenueTitle { get; set; }
        public string VenueDescription { get; set; }
        public string VenueNotes { get; set; }
        public string VenuePrefix { get; set; }
        public bool VenueEnabled { get; set; }
        public string VenueCode { get; set; }
        public bool DORSVenue { get; set; }
    }
}
