//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAM.Atlas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwZData_FiveYearDate
    {
        public Nullable<int> YearNumber { get; set; }
        public int MonthNumber { get; set; }
        public int DayNumber { get; set; }
        public Nullable<System.DateTime> TheDate { get; set; }
    }
}
